name = "DelPezzoBlekherman"
version = "0.1.0"
keywords = ["math", "algebraic-geometry", "convexity", "sums-of-squares"]
defaultTargets = ["DelPezzoBlekherman"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0-rc2"

[[lean_lib]]
name = "DelPezzoBlekherman"
