import Mathlib.Analysis.Convex.Cone.Basic
import Mathlib.Topology.Algebra.Module.FiniteDimension

noncomputable section

universe u v

open Set

namespace SOSConeDual

variable {V : Type u} {Q : Type v}
  [AddCommGroup Q] [Module ℝ Q]

/-- The convex cone generated by all degree-one squares.  The map `sq` is kept abstract so the
result applies to any finite-dimensional graded multiplication model. -/
def sosCone (sq : V → Q) : ConvexCone ℝ Q :=
  ConvexCone.hull ℝ (Set.range sq)

@[simp]
theorem square_mem_sosCone (sq : V → Q) (x : V) : sq x ∈ sosCone sq :=
  ConvexCone.subset_hull ⟨x, rfl⟩

/-- Dual characterization: it suffices to test a linear functional on individual squares. -/
theorem nonnegative_on_sosCone_iff
    (sq : V → Q) (ell : Q →ₗ[ℝ] ℝ) :
    (∀ q ∈ sosCone sq, 0 ≤ ell q) ↔ ∀ x, 0 ≤ ell (sq x) := by
  constructor
  · intro h x
    exact h (sq x) (square_mem_sosCone sq x)
  · intro h
    let C : ConvexCone ℝ Q := {
      carrier := {q | 0 ≤ ell q}
      smul_mem' := by
        intro r hr q hq
        simpa using mul_nonneg hr.le hq
      add_mem' := by
        intro q hq q' hq'
        simpa using add_nonneg hq hq' }
    have hsC : Set.range sq ⊆ C := by
      rintro q ⟨x, rfl⟩
      exact h x
    have hle : sosCone sq ≤ C := ConvexCone.hull_min hsC
    intro q hq
    exact hle hq

section Topological

variable [TopologicalSpace Q] [IsTopologicalAddGroup Q] [ContinuousSMul ℝ Q]

/-- Taking the closure of the SOS cone does not change its continuous dual. -/
theorem nonnegative_on_closure_sosCone_iff
    (sq : V → Q) (ell : Q →L[ℝ] ℝ) :
    (∀ q ∈ closure (sosCone sq : Set Q), 0 ≤ ell q) ↔ ∀ x, 0 ≤ ell (sq x) := by
  constructor
  · intro h x
    exact h (sq x) (subset_closure (square_mem_sosCone sq x))
  · intro h
    have hcone : (sosCone sq : Set Q) ⊆ {q | 0 ≤ ell q} := by
      intro q hq
      exact (nonnegative_on_sosCone_iff sq ell.toLinearMap).mpr h q hq
    have hclosed : IsClosed {q : Q | 0 ≤ ell q} :=
      isClosed_Ici.preimage ell.continuous
    exact closure_minimal hcone hclosed

/-- If the generated SOS cone is closed, the preceding statement specializes to its ordinary
dual characterization without mentioning closure. -/
theorem nonnegative_on_sosCone_iff_of_isClosed
    (sq : V → Q) (hclosed : IsClosed (sosCone sq : Set Q))
    (ell : Q →L[ℝ] ℝ) :
    (∀ q ∈ sosCone sq, 0 ≤ ell q) ↔ ∀ x, 0 ≤ ell (sq x) := by
  simpa [hclosed.closure_eq] using nonnegative_on_closure_sosCone_iff sq ell

end Topological

end SOSConeDual
