import DelPezzoBlekherman.Geometry.Proj.RadicalMap
import DelPezzoBlekherman.Geometry.Proj.Finite
import DelPezzoBlekherman.Fiber.ReducedAlgebra
import DelPezzoBlekherman.Geometry.Proj.KernelFiber
import DelPezzoBlekherman.Algebra.HVectorCertificate
import DelPezzoBlekherman.Algebra.SoclePairing
import DelPezzoBlekherman.Algebra.QuotientMultiplication
import DelPezzoBlekherman.Fiber.RealInertia
import DelPezzoBlekherman.Fiber.RealCount
import DelPezzoBlekherman.Fiber.RealFamily
import DelPezzoBlekherman.Fiber.ReciprocalHyperplane
import DelPezzoBlekherman.Fiber.MixedReciprocalHyperplane
import DelPezzoBlekherman.Fiber.ComplexBlock
import DelPezzoBlekherman.Fiber.EvaluationHyperplane
import DelPezzoBlekherman.SOS.KernelLength
import DelPezzoBlekherman.SOS.Compression
import DelPezzoBlekherman.SOS.ExactLength
import DelPezzoBlekherman.SOS.Perturbation
import DelPezzoBlekherman.Geometry.RealProjective.Topology
import DelPezzoBlekherman.SOS.RealProjectiveLength
import DelPezzoBlekherman.Analysis.AnalyticNonvanishing
import DelPezzoBlekherman.Geometry.RealProjective.PolynomialDensity
import DelPezzoBlekherman.Geometry.RealProjective.HVectorDensity
import DelPezzoBlekherman.Geometry.RealProjective.CoordinateFiber
import DelPezzoBlekherman.Geometry.RealProjective.GoodCoordinates
import DelPezzoBlekherman.Geometry.RealProjective.HVectorFiberFamily
import DelPezzoBlekherman.Fiber.ComplexBlockFamily
import DelPezzoBlekherman.Geometry.RealProjective.HVectorPairBound
import DelPezzoBlekherman.Fiber.RationalPointLift
import DelPezzoBlekherman.Geometry.RealProjective.CoordinateFiberLift
import DelPezzoBlekherman.Geometry.RealProjective.HVectorRationalLift
import DelPezzoBlekherman.Geometry.RealProjective.HVectorRealCount
import DelPezzoBlekherman.SOS.DenseFiberLength
import DelPezzoBlekherman.SOS.EvaluationContinuity
import DelPezzoBlekherman.SOS.FiberFamilyLength
import DelPezzoBlekherman.SOS.ProjectiveBasepoint
import DelPezzoBlekherman.SOS.SurjectiveLength
import DelPezzoBlekherman.Geometry.Proj.Surjectivity
import DelPezzoBlekherman.Convexity.ExtremeSeparator
import DelPezzoBlekherman.SOS.DualCone
import DelPezzoBlekherman.Convexity.ExtremeRayBase
import DelPezzoBlekherman.Convexity.RankOneExtreme
import DelPezzoBlekherman.Convexity.ConditionalSeparation

#print axioms MvPolynomial.gradedEval₂Hom
#print axioms MvPolynomial.irrelevant_le_radical_map_of_le_radical_span_range
#print axioms AlgebraicGeometry.ProjectiveSpectrum.comapFunOfRadical
#print axioms AlgebraicGeometry.Proj.mapOfRadical
#print axioms AlgebraicGeometry.Proj.mapOfRadical_isFinite_of_away_finite
#print axioms AlgebraicGeometry.Proj.projectiveAevalOfRadical_isFinite_of_away_finite
#print axioms HomogeneousLocalization.Away.map_finite_of_toRingHom_finite
#print axioms AlgebraicGeometry.Proj.projectiveAevalOfRadical_isFinite_of_toRingHom_finite
#print axioms AlgebraicGeometry.Proj.projectiveAevalOfRadical_isFinite_and_finrank_eq_add_two_of_basis
#print axioms AlgebraicGeometry.Proj.projectiveAevalOfRadical_isFinite_and_reduced_fiber_card_eq_add_two_of_basis
#print axioms Algebra.map_discr_eq_discr_tensorProduct_basis
#print axioms Ideal.isReduced_fiber_of_discr_not_mem
#print axioms Ideal.discr_ne_zero_of_genericFiber_isField_of_charZero
#print axioms Ideal.isReduced_genericFiber_of_isField_of_charZero
#print axioms Ideal.isField_genericFiber_of_finite_of_isDomain
#print axioms Ideal.discr_ne_zero_of_finite_of_isDomain_of_charZero
#print axioms AlgebraicGeometry.Proj.projectiveAevalOfRadical_isFinite_and_fiber_card_eq_add_two_of_discr_not_mem
#print axioms AlgebraicGeometry.Proj.projectiveAevalOfRadical_isFinite_and_discr_ne_zero_of_basis
#print axioms HVectorOneCOneFreeCertificate.finBasis
#print axioms AlgebraicGeometry.Proj.projectiveAevalOfRadical_isFinite_and_discr_ne_zero_of_hVectorOneCOne
#print axioms AlgebraicGeometry.Proj.projectiveAevalOfRadical_hVectorOneCOne_fiber_card_eq_add_two
#print axioms LinearMap.BilinForm.ker_pullbackQuotient_eq
#print axioms ArtinianGorensteinDegreeOneCertificate.nondegenerate_soclePairing_of_annihilator
#print axioms ArtinianGorensteinDegreeOneCertificate.parameterSpace_finrank_and_hankelRank_of_socleAnnihilator
#print axioms ArtinianGorensteinDegreeOneCertificate.socleFunctional_injective
#print axioms ArtinianGorensteinDegreeOneCertificate.nondegenerate_soclePairing_of_nonzero_functional
#print axioms ArtinianGorensteinDegreeOneCertificate.socleFunctional_ne_zero_of_pullbackQuotient_ne_zero
#print axioms ArtinianGorensteinDegreeOneCertificate.parameterSpace_finrank_and_hankelRank_of_nonzeroSocleFunctional
#print axioms ArtinianGorensteinDegreeOneCertificate.parameterSpace_finrank_and_hankelRank_of_nonzeroHankel
#print axioms ArtinianGorensteinDegreeOneCertificate.hankelForm_eq_pullbackQuotient_of_factorization
#print axioms ArtinianGorensteinDegreeOneCertificate.hankelKernel_eq_parameterSpace_and_finrank_and_rank_of_factorization
#print axioms ArtinianGorensteinDegreeOneCertificate.parameterSpace_le_ker_multiplicationToQuotient
#print axioms ArtinianGorensteinDegreeOneCertificate.parameterSpace_le_flipKer_multiplicationToQuotient
#print axioms ArtinianGorensteinDegreeOneCertificate.quotientMultiplication_mk
#print axioms ArtinianGorensteinDegreeOneCertificate.descendedSocleFunctional_mk
#print axioms ArtinianGorensteinDegreeOneCertificate.descendedSocleFunctional_quotientMultiplication_mk
#print axioms ArtinianGorensteinDegreeOneCertificate.quotientMultiplication_symmetric
#print axioms ArtinianGorensteinDegreeOneCertificate.hankelForm_ne_zero_of_tensorProduct_lift_surjective
#print axioms ArtinianGorensteinDegreeOneCertificate.hankelKernel_eq_parameterSpace_and_finrank_and_rank_of_ambientMultiplication
#print axioms ArtinianGorensteinDegreeOneCertificate.hankelKernel_eq_parameterSpace_and_finrank_and_rank_of_degreeTwoGenerated
#print axioms QuadraticForm.sigNeg_restrict_le
#print axioms QuadraticForm.NonrealPairNegativeDirections.card_le_one_of_restrict
#print axioms IsArtinianRing.real_reduced_fiber_rational_point_dichotomy_of_restricted_inertia
#print axioms IsArtinianRing.reducedFiniteAlgEquivPi
#print axioms Ideal.natCard_primeSpectrum_fiber_eq_add_two
#print axioms Algebra.isReduced_of_det_traceForm_ne_zero
#print axioms QuadraticClosedPoint.nonempty_residueAlgEquiv_complex
#print axioms IsArtinianRing.real_reduced_fiber_count_dichotomy
#print axioms IsArtinianRing.real_reduced_fiber_rational_point_dichotomy
#print axioms IsArtinianRing.real_finrank_eq_rationalClosedPoint_add_two_mul_quadraticClosedPoint
#print axioms IsArtinianRing.add_two_eq_rationalClosedPoint_add_two_mul_quadraticClosedPoint
#print axioms IsArtinianRing.exists_rationalClosedPoint_of_finrank_add_two_of_pair_le_one
#print axioms RealFiberFamily.count_eq_add_two_on
#print axioms RealFiberFamily.pairCount_le_one_on
#print axioms RealFiberFamily.realCount_eq_zero
#print axioms RealFiberFamily.realCount_eq_zero_of_not_mem_range_of_lift
#print axioms IsArtinianRing.real_fiber_count_dichotomy_of_basis_discr_ne_zero
#print axioms IsArtinianRing.real_fiber_rational_point_dichotomy_of_basis_discr_ne_zero
#print axioms LinearMap.exists_smul_of_ker_le_ker
#print axioms ReciprocalHyperplane.reciprocal_identity_of_radical
#print axioms ReciprocalHyperplane.radical_of_reciprocal_identity
#print axioms ReciprocalHyperplane.ncard_negative_eq_one_of_reciprocal_identity
#print axioms MixedReciprocalHyperplane.two_mul_re_sq_div_mk
#print axioms MixedReciprocalHyperplane.reciprocal_identity_mk_iff
#print axioms MixedReciprocalHyperplane.re_nonpos_of_nonnegative_on_relation_one
#print axioms MixedReciprocalHyperplane.re_neg_of_nonnegative_on_relation_one
#print axioms MixedReciprocalHyperplane.reciprocal_identity_of_radical
#print axioms MixedReciprocalHyperplane.radical_of_reciprocal_identity
#print axioms QuadraticForm.NonrealPairNegativeDirections.ofWeightedCoordinates
#print axioms QuadraticForm.NonrealPairNegativeDirections.ofComplexBlocks
#print axioms QuadraticForm.NonrealPairNegativeDirections.card_le_one_of_nonnegative_relationOne
#print axioms IsArtinianRing.real_reduced_fiber_rational_point_dichotomy_of_complexBlocks
#print axioms IsArtinianRing.real_reduced_fiber_rational_point_dichotomy_of_normalizedComplexBlocks
#print axioms EvaluationHyperplane.partners_of_three_le_card
#print axioms EvaluationHyperplane.unique_relation_coefficients
#print axioms EvaluationHyperplane.span_products_eq_top_of_three_le_card
#print axioms EvaluationHyperplane.eval₂_surjective_of_three_le_card
#print axioms EvaluationHyperplane.eval₂LinearEquivOfThreeLeCard
#print axioms SOSKernelLength.each_mem_ker_of_sum_apply_self_eq_zero
#print axioms SOSKernelLength.finrank_ker_le_card
#print axioms SOSKernelLength.span_eq_of_no_common_zero
#print axioms SOSKernelLength.boundary_sos_length_ge_add_one_of_basepoints
#print axioms SOSKernelLength.no_common_zero_of_strictlyPositive_sos
#print axioms SOSKernelLength.supplied_add_one_representation_is_minimal
#print axioms SOSCompression.updateScalar_identity
#print axioms SOSCompression.rankOne_update
#print axioms SOSCompression.compress_one_extra_explicit
#print axioms SOSCompression.rankOne_update_span_eq
#print axioms SOSCompression.compress_list_into_family
#print axioms SOSCompression.compress_finset_into_family
#print axioms SOSCompression.compress_to_spanning_subfamily
#print axioms SOSCompression.exists_basis_subfamily
#print axioms SOSCompression.exists_compression_to_finrank_span
#print axioms SOSKernelLength.boundary_sos_has_exact_minimal_length
#print axioms SOSKernelLength.exists_mem_dense_outside_compact_range
#print axioms SOSKernelLength.real_count_pos_of_total_eq_add_two_and_pair_le_one
#print axioms SOSKernelLength.boundary_sos_length_ge_add_one_of_reduced_fiber_perturbation
#print axioms SOSKernelLength.boundary_sos_has_exact_minimal_length_of_reduced_fiber_perturbation
#print axioms RealProjectiveTopology.continuous_normalize
#print axioms RealProjectiveTopology.continuous_directionOf
#print axioms RealProjectiveTopology.directionOf_eq_iff_exists_smul
#print axioms RealProjectiveTopology.normalize_surjective
#print axioms RealProjectiveTopology.directionOf_surjective
#print axioms RealProjectiveTopology.dense_image_directionOf_of_dense
#print axioms RealProjectiveTopology.dense_image_directionOf_continuousLinearEquiv
#print axioms RealProjectiveTopology.basisContinuousLinearEquiv
#print axioms AnalyticNonzeroDense.dense_setOf_ne_zero_of_analytic
#print axioms MvPolynomial.dense_setOf_eval_ne_zero
#print axioms MvPolynomial.dense_directionOf_image_eval_ne_zero
#print axioms MvPolynomial.dense_directionOf_image_equiv_eval_ne_zero
#print axioms AlgebraicGeometry.Proj.dense_real_projective_discr_locus_of_hVectorOneCOne
#print axioms AlgebraicGeometry.Proj.dense_real_projective_discr_locus_equiv_of_hVectorOneCOne
#print axioms AlgebraicGeometry.Proj.dense_real_projective_discr_locus_basis_of_hVectorOneCOne
#print axioms AlgebraicGeometry.Proj.realHVectorDiscr_ne_zero
#print axioms AlgebraicGeometry.Proj.dense_realHVectorOmega
#print axioms RealProjectiveCoordinateFiber.fiber_finrank_eq_card
#print axioms RealProjectiveCoordinateFiber.fiber_isReduced_of_eval_discr_ne_zero
#print axioms RealProjectiveCoordinateFiber.hVector_fiber_finrank_eq_add_two
#print axioms RealProjectiveCoordinateFiber.hVector_fiber_isReduced
#print axioms MvPolynomial.dense_setOf_hasGoodCoordinates
#print axioms MvPolynomial.eval_goodCoordinates_ne_zero
#print axioms MvPolynomial.directionOf_goodCoordinates
#print axioms RealProjectiveCoordinateFiber.fiberAt_finrank_eq_card
#print axioms RealProjectiveCoordinateFiber.fiberAt_isReduced_of_eval_discr_ne_zero
#print axioms RealProjectiveCoordinateFiber.dense_hVectorGoodOmega
#print axioms RealProjectiveCoordinateFiber.hVectorGoodFiber_finrank_eq_add_two
#print axioms RealProjectiveCoordinateFiber.hVectorGoodFiber_isReduced
#print axioms RealFiberFamily.pairCount_le_one_of_normalizedComplexBlocks
#print axioms RealProjectiveCoordinateFiber.hVectorGoodFiber_pairCount_le_one_of_normalizedComplexBlocks
#print axioms RationalClosedPoint.residueAlgEquiv
#print axioms RationalClosedPoint.algHom
#print axioms RealProjectiveCoordinateFiber.sourceAlgHomOfRationalFiberPoint_algebraMap
#print axioms RealProjectiveCoordinateFiber.hVectorSourceAlgHomOfRationalFiberPoint_algebraMap
#print axioms RealProjectiveCoordinateFiber.hVectorSourceAlgHomOfRationalFiberPoint_generator
#print axioms RealProjectiveCoordinateFiber.directionOf_hVectorSourceAlgHomOfRationalFiberPoint_generators
#print axioms RealProjectiveCoordinateFiber.hVectorGoodFiber_realCount_eq_zero_outside_range
#print axioms RealProjectiveCoordinateFiber.hVectorGoodFiber_realCount_eq_zero_outside_generatorDirection
#print axioms SOSKernelLength.boundary_sos_has_exact_minimal_length_of_ordinary_continuity_and_dense_locus
#print axioms SOSKernelLength.continuous_dual_evaluation_of_continuous_on_basis
#print axioms SOSKernelLength.boundary_sos_has_exact_minimal_length_of_real_fiber_family
#print axioms SOSKernelLength.restrictedEval_ne_zero_of_strictlyPositive_sos
#print axioms SOSKernelLength.restrictContinuousDual_apply
#print axioms SOSKernelLength.continuous_realProjectiveEval
#print axioms SOSKernelLength.realProjectiveEval_eq_directionOf_iff
#print axioms SOSKernelLength.boundary_sos_length_ge_add_one_of_real_projective_perturbation
#print axioms SOSKernelLength.boundary_sos_has_exact_minimal_length_of_real_projective_perturbation
#print axioms ProjectiveBasepoint.exists_nonzero_annihilator
#print axioms ProjectiveBasepoint.proper_subspace_has_common_zero_of_projective_surjective
#print axioms SOSKernelLength.boundary_sos_has_exact_minimal_length_of_projective_surjective
#print axioms AlgebraicGeometry.Proj.awayMap_injective_of_injective
#print axioms AlgebraicGeometry.Proj.mapOfRadical_surjective_of_degreeOne_cover
#print axioms AlgebraicGeometry.Proj.mapOfRadical_surjective_of_degreeOne_cover_of_finite_injective
#print axioms AlgebraicGeometry.Proj.projectiveAevalOfRadical_surjective_of_toRingHom_finite_injective
#print axioms AlgebraicGeometry.Proj.projectiveAevalOfRadical_isFinite_surjective_and_finrank_eq_add_two_of_basis
#print axioms AlgebraicGeometry.Proj.projectiveAevalOfRadical_isFinite_surjective_discr_and_rank_of_hVectorOneCOne
#print axioms ExtremeSeparator.exists_extremePoint_apply_neg
#print axioms ExtremeSeparator.properCone_separates
#print axioms SOSConeDual.nonnegative_on_sosCone_iff
#print axioms SOSConeDual.nonnegative_on_closure_sosCone_iff
#print axioms ExtremeRayBase.isExtremeRay_of_extremePoint_base
#print axioms ExtremeRayBase.exists_extremeRay_apply_neg_of_compact_base
#print axioms PSDRangeOneExtreme.ker_add_eq_inf
#print axioms PSDRangeOneExtreme.eq_smul_rankOne_of_ker_le
#print axioms PSDRangeOneExtreme.rankOne_extreme_decomposition
#print axioms ConditionalSeparation.exists_normalized_extreme_separator
#print axioms ConditionalSeparation.exists_basepointFree_extreme_separator
