/-
Copyright (c) 2026 Codex. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import DelPezzoBlekherman.Algebra.StandardGradedMultiplication
import Mathlib.RingTheory.Regular.RegularSequence

/-!
# Native arithmetically Gorenstein boundary

This file gives the algebraic rank argument a paper-facing input.  The input is operational:
the chosen degree-one parameters are a regular sequence in the coordinate ring, their quotient
is Artinian, and multiplication on the degree-one reduction is a perfect pairing into its
one-dimensional degree-two socle.  In particular, none of the proof-only Hilbert, exact-sequence,
or parameter-product certificates occurs in the public rank theorem below.

The Hilbert-series equation is deliberately a separate hypothesis, as it is in Theorem 1.1.
The implementation converts the native hypotheses to the older internal interfaces only inside
the proof.
-/

noncomputable section

universe u v

open PowerSeries

namespace DelPezzoBlekherman

open ArtinianGorensteinDegreeOneCertificate

variable {K : Type u} {A : Type v}
variable [Field K] [CommRing A] [Algebra K A]

/-- The ideal generated by a chosen tuple of homogeneous degree-one parameters. -/
def degreeOneParameterIdeal
    (𝒜 : ℕ → Submodule K A) {n : ℕ} (parameters : Fin n → 𝒜 1) : Ideal A :=
  Ideal.span (Set.range fun i ↦ (parameters i : A))

/-- Operational form of the arithmetically Gorenstein hypothesis along the degree-one
parameters used in the proof.

* `regular` is mathlib's ring-theoretic regular-sequence predicate, applied to the actual
  homogeneous elements of the coordinate ring;
* `artinian` says that their ring quotient is the Artinian reduction;
* `socleFinrankOne` and `perfectSocleMultiplication` state the `(1,c,1)` Gorenstein conclusion
  on the concrete degree-one and degree-two component quotients.

This does not contain, extend, or mention any of the older project-specific bridge
certificates. -/
structure IsArithmeticallyGorenstein
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    {m : ℕ} (parameters : Fin (m + 1) → 𝒜 1) : Prop where
  regular : RingTheory.Sequence.IsRegular A
    (List.ofFn fun i ↦ (parameters i : A))
  artinian : IsArtinianRing (A ⧸ degreeOneParameterIdeal 𝒜 parameters)
  socleFinrankOne :
    Module.finrank K
      (𝒜 2 ⧸ parameterProductSubmodule
        (Submodule.span K (Set.range parameters))
        (gradedDegreeOneMultiplication 𝒜)) = 1
  perfectSocleMultiplication :
    (parameterProductQuotientMultiplication
      (Submodule.span K (Set.range parameters))
      (gradedDegreeOneMultiplication 𝒜)
      (gradedDegreeOneMultiplication_symmetric 𝒜)).Nondegenerate

/-- The literal Hilbert-series equation from the paper supplies finite-dimensionality of the
degree-one component.  The equation is kept unbundled in the statement so callers do not need
to manufacture `DelPezzoHilbertSeriesCertificate`. -/
theorem moduleFinite_degreeOne_of_delPezzoHilbertSeries
    (𝒜 : ℕ → Submodule K A) {m c : ℕ}
    (hHilbert : ∀ d,
      (Module.finrank K (𝒜 d) : ℤ) = coeff d (delPezzoHilbertSeries m c)) :
    Module.Finite K (𝒜 1) := by
  exact (DelPezzoHilbertSeriesCertificate.mk hHilbert).moduleFinite_one

/-- Native algebraic rank endpoint for the Theorem 4.3 step used in Theorem 1.1(ii).

The public assumptions are the actual graded coordinate-ring pieces, standard-graded
degree-two generation, a nonzero degree-two functional, the chosen regular degree-one
parameters, the literal Hilbert-series equation, and the operational arithmetically Gorenstein
property.  The conclusion identifies the actual Hankel kernel, proves that it has dimension
`m + 1`, and proves rank `c`.

In particular, the signature contains none of
`HVectorOneCOneFreeCertificate`, `DelPezzoHilbertSeriesCertificate`,
`SuccessiveDegreeOneReductionComponentExactSequences`, or
`ParameterProductGorensteinCertificate`. -/
theorem hankelKernel_eq_parameterSpan_and_rank_of_arithmeticallyGorenstein
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (hgenerated : DegreeTwoGeneratedByDegreeOne 𝒜)
    (ell : 𝒜 2 →ₗ[K] K) (hell : ell ≠ 0)
    {m c : ℕ}
    (parameters : Fin (m + 1) → 𝒜 1)
    (hparameters : LinearIndependent K parameters)
    (hparametersKernel : ∀ i,
      parameters i ∈ LinearMap.ker ((gradedDegreeOneMultiplication 𝒜).compr₂ ell))
    (hHilbert : ∀ d,
      (Module.finrank K (𝒜 d) : ℤ) = coeff d (delPezzoHilbertSeries m c))
    (hAG : IsArithmeticallyGorenstein 𝒜 parameters) :
    LinearMap.ker ((gradedDegreeOneMultiplication 𝒜).compr₂ ell) =
        Submodule.span K (Set.range parameters) ∧
      Module.finrank K
          (LinearMap.ker ((gradedDegreeOneMultiplication 𝒜).compr₂ ell)) = m + 1 ∧
      @LinearMap.BilinForm.finiteRank K (𝒜 1) _ _ _
        (moduleFinite_degreeOne_of_delPezzoHilbertSeries 𝒜 hHilbert)
        ((gradedDegreeOneMultiplication 𝒜).compr₂ ell) = c := by
  let hHilbertInternal : DelPezzoHilbertSeriesCertificate 𝒜 m c :=
    ⟨hHilbert⟩
  let hPairingInternal : ParameterProductPerfectPairingCertificate
      (Submodule.span K (Set.range parameters))
      (gradedDegreeOneMultiplication 𝒜)
      (gradedDegreeOneMultiplication_symmetric 𝒜) :=
    { socleFinrankOne := hAG.socleFinrankOne
      perfect := hAG.perfectSocleMultiplication }
  let _ : Module.Finite K (𝒜 1) :=
    moduleFinite_degreeOne_of_delPezzoHilbertSeries 𝒜 hHilbert
  have hR₁ : Module.finrank K (𝒜 1) = m + c + 1 := by
    simpa only [hilbertDegreeOne, add_assoc, add_comm, add_left_comm] using
      hHilbertInternal.finrank_one
  have hKernelRank := hankelKernel_eq_parameterSpan_and_rank_of_parameters_mem_hankelKernel
    (gradedDegreeOneMultiplication 𝒜)
    (gradedDegreeOneMultiplication_symmetric 𝒜) ell hell
    (symmetricSquare_gradedDegreeOneMultiplication_surjective 𝒜 hgenerated)
    parameters hparameters hparametersKernel hPairingInternal hR₁
  refine ⟨hKernelRank.1, ?_, hKernelRank.2⟩
  rw [hKernelRank.1, finrank_span_eq_card hparameters]
  simp

end DelPezzoBlekherman
