/-
Copyright (c) 2026 Codex. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import DelPezzoBlekherman.Algebra.NativeGorenstein
import DelPezzoBlekherman.Geometry.Proj.GradedEvaluation
import Mathlib.RingTheory.MvPolynomial.Ideal
import Mathlib.RingTheory.Spectrum.Prime.FreeLocus
import Mathlib.RingTheory.TensorProduct.Quotient

/-!
# Generic rank from the native parameter reduction

This file identifies the generic rank of a coordinate ring over its polynomial parameter
subring with the dimension of the actual parameter quotient. Combined with the native
Hilbert-series calculation in NativeGorenstein, this gives rank c + 2 without a global
module basis or an HVectorOneCOneFreeCertificate.

The remaining algebraic input is flatness over the parameter polynomial ring. For the
Cohen--Macaulay coordinate rings in the paper this is the standard regular-parameter
consequence; it is stated explicitly here until that commutative-algebra bridge is available.
-/

noncomputable section

open PowerSeries

namespace DelPezzoBlekherman

universe u v

variable {K : Type u} {C : Type v}

/-- The kernel of polynomial evaluation at the origin is the irrelevant ideal. -/
theorem ker_constantCoeff_eq_idealOfVars
    {I : Type*} [Field K] :
    RingHom.ker (MvPolynomial.constantCoeff : MvPolynomial I K →+* K) =
      MvPolynomial.idealOfVars I K := by
  ext p
  rw [RingHom.mem_ker]
  rw [← pow_one (MvPolynomial.idealOfVars I K)]
  rw [MvPolynomial.mem_pow_idealOfVars_iff']
  simp only [Nat.lt_one_iff, MvPolynomial.constantCoeff_eq]
  constructor
  · intro hp x hx
    rwa [(Finsupp.degree_eq_zero_iff x).mp hx]
  · intro hp
    exact hp 0 rfl

/-- The graded evaluation homomorphism determined by degree-one parameters. -/
def degreeOneParameterAevalHom
    [Field K] [CommRing C] [Algebra K C]
    (𝒞 : ℕ → Submodule K C) [SetLike.GradedMonoid 𝒞]
    {n : ℕ} (parameters : Fin n → 𝒞 1) :=
  MvPolynomial.standardGradedAevalHom 𝒞
    (fun i ↦ (parameters i : C)) (fun i ↦ (parameters i).2)

/-- The irrelevant ideal maps to the ideal generated by the chosen parameters. -/
theorem map_idealOfVars_degreeOneParameterAevalHom
    [Field K] [CommRing C] [Algebra K C]
    (𝒞 : ℕ → Submodule K C) [SetLike.GradedMonoid 𝒞]
    {n : ℕ} (parameters : Fin n → 𝒞 1) :
    (MvPolynomial.idealOfVars (Fin n) K).map
        (degreeOneParameterAevalHom 𝒞 parameters).toRingHom =
      degreeOneParameterIdeal 𝒞 parameters := by
  unfold MvPolynomial.idealOfVars degreeOneParameterIdeal
  rw [Ideal.map_span]
  congr 1
  ext x
  simp [degreeOneParameterAevalHom,
    MvPolynomial.standardGradedAevalHom_apply_X]

/-- For a finite flat coordinate ring over its parameter polynomial ring, generic rank equals
the dimension of the actual Artinian parameter reduction. This is basis-free: the proof
specializes the finite flat module at the origin and identifies that fiber with the parameter
quotient. -/
theorem genericRank_eq_degreeOneParameterIdeal_quotient_of_flat
    [Field K] [CommRing C] [Algebra K C]
    (𝒞 : ℕ → Submodule K C) [SetLike.GradedMonoid 𝒞]
    {n : ℕ} (parameters : Fin n → 𝒞 1)
    (hflat : let f := degreeOneParameterAevalHom 𝒞 parameters
      letI := f.toRingHom.toAlgebra
      Module.Flat (MvPolynomial (Fin n) K) C)
    (hfinite : let f := degreeOneParameterAevalHom 𝒞 parameters
      letI := f.toRingHom.toAlgebra
      Module.Finite (MvPolynomial (Fin n) K) C) :
    let f := degreeOneParameterAevalHom 𝒞 parameters
    letI := f.toRingHom.toAlgebra
    Module.finrank (MvPolynomial (Fin n) K) C =
      Module.finrank K
        (C ⧸ (degreeOneParameterIdeal 𝒞 parameters).restrictScalars K) := by
  classical
  let P := MvPolynomial (Fin n) K
  let f := degreeOneParameterAevalHom 𝒞 parameters
  letI : Algebra P C := f.toRingHom.toAlgebra
  let p : Ideal P := RingHom.ker MvPolynomial.constantCoeff
  have hconstSurj : Function.Surjective
      (MvPolynomial.constantCoeff : P →+* K) := by
    intro x
    exact ⟨MvPolynomial.C x, by simp⟩
  letI : p.IsMaximal := RingHom.ker_isMaximal_of_surjective _ hconstSurj
  letI : p.IsPrime := inferInstance
  let hQuotIsField : IsField (P ⧸ p) :=
    (Ideal.Quotient.maximal_ideal_iff_isField_quotient p).mp inferInstance
  letI : Field (P ⧸ p) := hQuotIsField.toField
  letI : Module.Flat P C := hflat
  letI : Module.Finite P C := hfinite
  let Q := C ⧸ p.map (algebraMap P C)
  let eBase : (P ⧸ p) ≃+* K :=
    RingHom.quotientKerEquivOfSurjective hconstSurj
  let eQuot : Q ≃ₐ[P ⧸ p] TensorProduct P (P ⧸ p) C :=
    Algebra.TensorProduct.quotIdealMapEquivQuotTensor C p
  let eCancel : TensorProduct (P ⧸ p) p.ResidueField
      (TensorProduct P (P ⧸ p) C) ≃ₐ[p.ResidueField]
      p.Fiber C :=
    Algebra.TensorProduct.cancelBaseChange P (P ⧸ p) p.ResidueField p.ResidueField C
  have hbaseFinrank : Module.finrank (P ⧸ p) Q = Module.finrank K Q := by
    apply Algebra.finrank_eq_of_equiv_equiv eBase (RingEquiv.refl Q)
    apply RingHom.ext
    intro a
    induction a using Quotient.inductionOn' with
    | _ a =>
      apply Ideal.Quotient.eq.mpr
      have ha : MvPolynomial.C (MvPolynomial.constantCoeff a) - a ∈ p := by
        change MvPolynomial.constantCoeff
          (MvPolynomial.C (MvPolynomial.constantCoeff a) - a) = 0
        simp
      have hmap := Ideal.mem_map_of_mem (algebraMap P C) ha
      have heBase : eBase (Ideal.Quotient.mk p a) =
          MvPolynomial.constantCoeff a := by
        exact RingHom.quotientKerEquivOfSurjective_apply_mk hconstSurj a
      change algebraMap K C (eBase (Ideal.Quotient.mk p a)) -
          algebraMap P C a ∈ p.map (algebraMap P C)
      rw [heBase]
      have hC : algebraMap P C
          (MvPolynomial.C (MvPolynomial.constantCoeff a)) =
          algebraMap K C (MvPolynomial.constantCoeff a) := by
        change f.toRingHom (MvPolynomial.C (MvPolynomial.constantCoeff a)) = _
        simp [f, degreeOneParameterAevalHom,
          MvPolynomial.standardGradedAevalHom, MvPolynomial.gradedAevalHom,
          MvPolynomial.gradedEval₂Hom]
      rw [← hC]
      simpa using hmap
  have hfiberQuot :
      Module.finrank p.ResidueField (p.Fiber C) = Module.finrank (P ⧸ p) Q := by
    letI : Module.Finite (P ⧸ p) (TensorProduct P (P ⧸ p) C) :=
      Module.Finite.base_change P (P ⧸ p) C
    letI : Module.Free (P ⧸ p) (TensorProduct P (P ⧸ p) C) :=
      Module.Free.of_divisionRing _ _
    rw [← eCancel.toLinearEquiv.finrank_eq, Module.finrank_baseChange,
      ← eQuot.toLinearEquiv.finrank_eq]
  have hmap : p.map (algebraMap P C) = degreeOneParameterIdeal 𝒞 parameters := by
    change (RingHom.ker MvPolynomial.constantCoeff).map f.toRingHom = _
    rw [ker_constantCoeff_eq_idealOfVars]
    exact map_idealOfVars_degreeOneParameterAevalHom 𝒞 parameters
  calc
    Module.finrank P C = Module.finrank p.ResidueField (p.Fiber C) :=
      (Ideal.finrank_fiber_eq_finrank p).symm
    _ = Module.finrank (P ⧸ p) Q := hfiberQuot
    _ = Module.finrank K Q := hbaseFinrank
    _ = Module.finrank K
        (C ⧸ (degreeOneParameterIdeal 𝒞 parameters).restrictScalars K) := by
      change Module.finrank K (C ⧸ p.map (algebraMap P C)) =
        Module.finrank K
          (C ⧸ (degreeOneParameterIdeal 𝒞 parameters).restrictScalars K)
      rw [hmap]
      exact (Submodule.Quotient.restrictScalarsEquiv K
        (degreeOneParameterIdeal 𝒞 parameters : Submodule C C)).finrank_eq.symm

/-- Native rank c + 2 over the parameter polynomial ring. The rank follows from flatness,
regularity, degreewise finiteness, and the literal Hilbert-series formula; no chosen module basis
or project-specific Hilbert-vector certificate appears in the statement. -/
theorem genericRank_eq_add_two_of_flat
    [Field K] [CommRing C] [Algebra K C]
    (𝒞 : ℕ → Submodule K C) [GradedRing 𝒞]
    {m c : ℕ} (parameters : Fin (m + 1) → 𝒞 1)
    (hregular : RingTheory.Sequence.IsRegular C
      (List.ofFn fun i ↦ (parameters i : C)))
    (hcomponentFinite : ∀ d, Module.Finite K (𝒞 d))
    (hHilbert : ∀ d,
      (Module.finrank K (𝒞 d) : ℤ) = coeff d (delPezzoHilbertSeries m c))
    (hflat : let f := degreeOneParameterAevalHom 𝒞 parameters
      letI := f.toRingHom.toAlgebra
      Module.Flat (MvPolynomial (Fin (m + 1)) K) C)
    (hfinite : let f := degreeOneParameterAevalHom 𝒞 parameters
      letI := f.toRingHom.toAlgebra
      Module.Finite (MvPolynomial (Fin (m + 1)) K) C) :
    let f := degreeOneParameterAevalHom 𝒞 parameters
    letI := f.toRingHom.toAlgebra
    Module.finrank (MvPolynomial (Fin (m + 1)) K) C = c + 2 := by
  let f := degreeOneParameterAevalHom 𝒞 parameters
  letI := f.toRingHom.toAlgebra
  change Module.finrank (MvPolynomial (Fin (m + 1)) K) C = c + 2
  rw [genericRank_eq_degreeOneParameterIdeal_quotient_of_flat
    𝒞 parameters hflat hfinite]
  exact degreeOneParameterIdeal_quotient_finrank
    𝒞 parameters hregular hcomponentFinite hHilbert

end DelPezzoBlekherman
