/-
Copyright (c) 2026 Codex. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import DelPezzoBlekherman.Algebra.StandardGradedMultiplication
import Mathlib.LinearAlgebra.Isomorphisms
import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal
import Mathlib.RingTheory.Regular.RegularSequence

/-!
# Native arithmetically Gorenstein boundary

This file gives the algebraic rank argument a paper-facing input.  The input is operational:
the chosen degree-one parameters are a regular sequence in the coordinate ring, their quotient
is Artinian, and multiplication on the degree-one reduction is a perfect pairing into its
one-dimensional degree-two socle.  In particular, none of the proof-only Hilbert, exact-sequence,
or parameter-product certificates occurs in the public rank theorem below.

The Hilbert-series equation is deliberately a separate hypothesis, as it is in Theorem 1.1.
The implementation converts the native hypotheses to the older internal interfaces only inside
the proof.
-/

noncomputable section

universe u v

open PowerSeries

namespace DelPezzoBlekherman

open ArtinianGorensteinDegreeOneCertificate

variable {K : Type u} {A : Type v}
variable [Field K] [CommRing A] [Algebra K A]

/-- The ideal generated by a chosen tuple of homogeneous degree-one parameters. -/
def degreeOneParameterIdeal
    (𝒜 : ℕ → Submodule K A) {n : ℕ} (parameters : Fin n → 𝒜 1) : Ideal A :=
  Ideal.span (Set.range fun i ↦ (parameters i : A))

/-- An ideal generated by homogeneous degree-one parameters is homogeneous.  This is the first
native ingredient needed to grade the actual Artinian parameter quotient, rather than supplying
its homogeneous pieces as an external certificate. -/
theorem degreeOneParameterIdeal_isHomogeneous
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    {n : ℕ} (parameters : Fin n → 𝒜 1) :
    (degreeOneParameterIdeal 𝒜 parameters).IsHomogeneous 𝒜 := by
  apply Ideal.homogeneous_span
  rintro x ⟨i, rfl⟩
  exact SetLike.isHomogeneousElem_coe (parameters i)

/-- The degree-`d` part of an ideal, viewed inside the degree-`d` homogeneous component. -/
def idealComponent
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ) : Submodule K (𝒜 d) :=
  (I.restrictScalars K).comap (𝒜 d).subtype

/-- The concrete degree-`d` vector space of the quotient by an ideal.  When the ideal is
homogeneous, these spaces are the homogeneous components of the quotient grading. -/
abbrev idealQuotientComponent
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ) :=
  (𝒜 d) ⧸ idealComponent 𝒜 I d

/-- The additive quotient map restricted to one homogeneous component.  Its codomain is the
underlying `K`-module quotient by the ideal; this is definitionally the additive quotient used by
the ring quotient, while making the linear structure explicit. -/
def componentQuotientMap
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ) :
    𝒜 d →ₗ[K] (A ⧸ I.restrictScalars K) :=
  (I.restrictScalars K).mkQ.comp (𝒜 d).subtype

@[simp]
theorem componentQuotientMap_ker
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ) :
    LinearMap.ker (componentQuotientMap 𝒜 I d) = idealComponent 𝒜 I d := by
  ext x
  simp [componentQuotientMap, idealComponent]

/-- A degreewise quotient component is canonically the image of that component in the actual
ring quotient.  This connects the finite-dimensional Hilbert calculation to the operational
Artinian quotient in `IsArithmeticallyGorenstein`. -/
noncomputable def idealQuotientComponentEquivRange
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ) :
    idealQuotientComponent 𝒜 I d ≃ₗ[K] LinearMap.range (componentQuotientMap 𝒜 I d) :=
  (Submodule.quotEquivOfEq _ _ (componentQuotientMap_ker 𝒜 I d).symm).trans
    (componentQuotientMap 𝒜 I d).quotKerEquivRange

/-- Finite-dimensional homogeneous pieces give finite-dimensional quotient pieces. -/
theorem moduleFinite_idealQuotientComponent
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ)
    [Module.Finite K (𝒜 d)] :
    Module.Finite K (idealQuotientComponent 𝒜 I d) := by
  infer_instance

/-- Multiplication by a fixed homogeneous element, between the corresponding homogeneous
components. -/
def gradedLeftMultiplication
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    {e : ℕ} (x : 𝒜 e) (d : ℕ) : 𝒜 d →ₗ[K] 𝒜 (e + d) where
  toFun y := ⟨(x : A) * (y : A), SetLike.mul_mem_graded x.2 y.2⟩
  map_add' y z := by
    apply Subtype.ext
    exact mul_add _ _ _
  map_smul' r y := by
    apply Subtype.ext
    simp

@[simp]
theorem gradedLeftMultiplication_apply
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    {e : ℕ} (x : 𝒜 e) (d : ℕ) (y : 𝒜 d) :
    ((gradedLeftMultiplication 𝒜 x d y : 𝒜 (e + d)) : A) = (x : A) * (y : A) :=
  rfl

/-- Multiplication preserves the degreewise part of every ideal. -/
theorem idealComponent_le_comap_gradedLeftMultiplication
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (I : Ideal A) {e : ℕ} (x : 𝒜 e) (d : ℕ) :
    idealComponent 𝒜 I d ≤
      (idealComponent 𝒜 I (e + d)).comap (gradedLeftMultiplication 𝒜 x d) := by
  intro y hy
  exact I.mul_mem_left (x : A) hy

/-- Multiplication by a homogeneous element on the actual degreewise ideal quotients.  For a
degree-one regular parameter this is the left-hand map in the desired Hilbert-function exact
sequence. -/
def idealQuotientComponentMul
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (I : Ideal A) {e : ℕ} (x : 𝒜 e) (d : ℕ) :
    idealQuotientComponent 𝒜 I d →ₗ[K] idealQuotientComponent 𝒜 I (e + d) :=
  (idealComponent 𝒜 I d).mapQ (idealComponent 𝒜 I (e + d))
    (gradedLeftMultiplication 𝒜 x d)
    (idealComponent_le_comap_gradedLeftMultiplication 𝒜 I x d)

@[simp]
theorem idealQuotientComponentMul_mk
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (I : Ideal A) {e : ℕ} (x : 𝒜 e) (d : ℕ) (y : 𝒜 d) :
    idealQuotientComponentMul 𝒜 I x d (Submodule.Quotient.mk y) =
      Submodule.Quotient.mk (gradedLeftMultiplication 𝒜 x d y) := by
  rfl

/-- Ring-theoretic regularity on the full ideal quotient implies injectivity of multiplication
on every homogeneous quotient component.  This discharges the injectivity field of the old
degreewise exact-sequence interface directly from native regularity. -/
theorem idealQuotientComponentMul_injective_of_isSMulRegular
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (I : Ideal A) {e : ℕ} (x : 𝒜 e) (d : ℕ)
    (hregular : IsSMulRegular (A ⧸ (I : Submodule A A)) (x : A)) :
    Function.Injective (idealQuotientComponentMul 𝒜 I x d) := by
  apply (injective_iff_map_eq_zero _).2
  intro q hq
  induction q using Submodule.Quotient.induction_on with
  | _ y =>
      rw [idealQuotientComponentMul_mk, Submodule.Quotient.mk_eq_zero] at hq
      rw [Submodule.Quotient.mk_eq_zero]
      exact mem_of_isSMulRegular_quotient_of_smul_mem hregular hq

/-- Inclusion of ideals induces inclusion of their degreewise components. -/
theorem idealComponent_mono
    (𝒜 : ℕ → Submodule K A) {I J : Ideal A} (hIJ : I ≤ J) (d : ℕ) :
    idealComponent 𝒜 I d ≤ idealComponent 𝒜 J d :=
  fun _ hy ↦ hIJ hy

/-- The canonical map on degreewise quotients induced by enlarging an ideal. -/
def idealQuotientComponentMapOfLE
    (𝒜 : ℕ → Submodule K A) {I J : Ideal A} (hIJ : I ≤ J) (d : ℕ) :
    idealQuotientComponent 𝒜 I d →ₗ[K] idealQuotientComponent 𝒜 J d :=
  (idealComponent 𝒜 I d).mapQ (idealComponent 𝒜 J d) LinearMap.id
    (by simpa using idealComponent_mono 𝒜 hIJ d)

@[simp]
theorem idealQuotientComponentMapOfLE_mk
    (𝒜 : ℕ → Submodule K A) {I J : Ideal A} (hIJ : I ≤ J) (d : ℕ)
    (y : 𝒜 d) :
    idealQuotientComponentMapOfLE 𝒜 hIJ d (Submodule.Quotient.mk y) =
      Submodule.Quotient.mk y := by
  rfl

/-- Enlarging an ideal gives a surjection on every degreewise quotient component. -/
theorem idealQuotientComponentMapOfLE_surjective
    (𝒜 : ℕ → Submodule K A) {I J : Ideal A} (hIJ : I ≤ J) (d : ℕ) :
    Function.Surjective (idealQuotientComponentMapOfLE 𝒜 hIJ d) := by
  intro q
  induction q using Submodule.Quotient.induction_on with
  | _ y => exact ⟨Submodule.Quotient.mk y, rfl⟩

/-- If the homogeneous multiplier belongs to the enlarged ideal, multiplication followed by
the quotient transition is zero.  This is the complex condition for the degreewise reduction
sequence; exactness will amount to the converse kernel inclusion. -/
theorem idealQuotientComponentMapOfLE_comp_mul_eq_zero
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    {I J : Ideal A} (hIJ : I ≤ J) {e : ℕ} (x : 𝒜 e) (hxJ : (x : A) ∈ J) (d : ℕ) :
    (idealQuotientComponentMapOfLE 𝒜 hIJ (e + d)).comp
        (idealQuotientComponentMul 𝒜 I x d) = 0 := by
  apply LinearMap.ext
  intro q
  induction q using Submodule.Quotient.induction_on with
  | _ y =>
      rw [LinearMap.comp_apply, idealQuotientComponentMul_mk,
        idealQuotientComponentMapOfLE_mk, LinearMap.zero_apply]
      rw [Submodule.Quotient.mk_eq_zero]
      exact J.mul_mem_right (y : A) hxJ

/-- Operational form of the arithmetically Gorenstein hypothesis along the degree-one
parameters used in the proof.

* `regular` is mathlib's ring-theoretic regular-sequence predicate, applied to the actual
  homogeneous elements of the coordinate ring;
* `artinian` says that their ring quotient is the Artinian reduction;
* `socleFinrankOne` and `perfectSocleMultiplication` state the `(1,c,1)` Gorenstein conclusion
  on the concrete degree-one and degree-two component quotients.

This does not contain, extend, or mention any of the older project-specific bridge
certificates. -/
structure IsArithmeticallyGorenstein
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    {m : ℕ} (parameters : Fin (m + 1) → 𝒜 1) : Prop where
  regular : RingTheory.Sequence.IsRegular A
    (List.ofFn fun i ↦ (parameters i : A))
  artinian : IsArtinianRing (A ⧸ degreeOneParameterIdeal 𝒜 parameters)
  socleFinrankOne :
    Module.finrank K
      (𝒜 2 ⧸ parameterProductSubmodule
        (Submodule.span K (Set.range parameters))
        (gradedDegreeOneMultiplication 𝒜)) = 1
  perfectSocleMultiplication :
    (parameterProductQuotientMultiplication
      (Submodule.span K (Set.range parameters))
      (gradedDegreeOneMultiplication 𝒜)
      (gradedDegreeOneMultiplication_symmetric 𝒜)).Nondegenerate

/-- The literal Hilbert-series equation from the paper supplies finite-dimensionality of the
degree-one component.  The equation is kept unbundled in the statement so callers do not need
to manufacture `DelPezzoHilbertSeriesCertificate`. -/
theorem moduleFinite_degreeOne_of_delPezzoHilbertSeries
    (𝒜 : ℕ → Submodule K A) {m c : ℕ}
    (hHilbert : ∀ d,
      (Module.finrank K (𝒜 d) : ℤ) = coeff d (delPezzoHilbertSeries m c)) :
    Module.Finite K (𝒜 1) := by
  exact (DelPezzoHilbertSeriesCertificate.mk hHilbert).moduleFinite_one

/-- Native algebraic rank endpoint for the Theorem 4.3 step used in Theorem 1.1(ii).

The public assumptions are the actual graded coordinate-ring pieces, standard-graded
degree-two generation, a nonzero degree-two functional, the chosen regular degree-one
parameters, the literal Hilbert-series equation, and the operational arithmetically Gorenstein
property.  The conclusion identifies the actual Hankel kernel, proves that it has dimension
`m + 1`, and proves rank `c`.

In particular, the signature contains none of
`HVectorOneCOneFreeCertificate`, `DelPezzoHilbertSeriesCertificate`,
`SuccessiveDegreeOneReductionComponentExactSequences`, or
`ParameterProductGorensteinCertificate`. -/
theorem hankelKernel_eq_parameterSpan_and_rank_of_arithmeticallyGorenstein
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (hgenerated : DegreeTwoGeneratedByDegreeOne 𝒜)
    (ell : 𝒜 2 →ₗ[K] K) (hell : ell ≠ 0)
    {m c : ℕ}
    (parameters : Fin (m + 1) → 𝒜 1)
    (hparameters : LinearIndependent K parameters)
    (hparametersKernel : ∀ i,
      parameters i ∈ LinearMap.ker ((gradedDegreeOneMultiplication 𝒜).compr₂ ell))
    (hHilbert : ∀ d,
      (Module.finrank K (𝒜 d) : ℤ) = coeff d (delPezzoHilbertSeries m c))
    (hAG : IsArithmeticallyGorenstein 𝒜 parameters) :
    LinearMap.ker ((gradedDegreeOneMultiplication 𝒜).compr₂ ell) =
        Submodule.span K (Set.range parameters) ∧
      Module.finrank K
          (LinearMap.ker ((gradedDegreeOneMultiplication 𝒜).compr₂ ell)) = m + 1 ∧
      @LinearMap.BilinForm.finiteRank K (𝒜 1) _ _ _
        (moduleFinite_degreeOne_of_delPezzoHilbertSeries 𝒜 hHilbert)
        ((gradedDegreeOneMultiplication 𝒜).compr₂ ell) = c := by
  let hHilbertInternal : DelPezzoHilbertSeriesCertificate 𝒜 m c :=
    ⟨hHilbert⟩
  let hPairingInternal : ParameterProductPerfectPairingCertificate
      (Submodule.span K (Set.range parameters))
      (gradedDegreeOneMultiplication 𝒜)
      (gradedDegreeOneMultiplication_symmetric 𝒜) :=
    { socleFinrankOne := hAG.socleFinrankOne
      perfect := hAG.perfectSocleMultiplication }
  let _ : Module.Finite K (𝒜 1) :=
    moduleFinite_degreeOne_of_delPezzoHilbertSeries 𝒜 hHilbert
  have hR₁ : Module.finrank K (𝒜 1) = m + c + 1 := by
    simpa only [hilbertDegreeOne, add_assoc, add_comm, add_left_comm] using
      hHilbertInternal.finrank_one
  have hKernelRank := hankelKernel_eq_parameterSpan_and_rank_of_parameters_mem_hankelKernel
    (gradedDegreeOneMultiplication 𝒜)
    (gradedDegreeOneMultiplication_symmetric 𝒜) ell hell
    (symmetricSquare_gradedDegreeOneMultiplication_surjective 𝒜 hgenerated)
    parameters hparameters hparametersKernel hPairingInternal hR₁
  refine ⟨hKernelRank.1, ?_, hKernelRank.2⟩
  rw [hKernelRank.1, finrank_span_eq_card hparameters]
  simp

end DelPezzoBlekherman
