/-
Copyright (c) 2026 Codex. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import DelPezzoBlekherman.Algebra.StandardGradedMultiplication
import Mathlib.LinearAlgebra.DirectSum.Finite
import Mathlib.LinearAlgebra.Isomorphisms
import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal
import Mathlib.RingTheory.Regular.RegularSequence

/-!
# Native arithmetically Gorenstein boundary

This file gives the algebraic rank argument a paper-facing input.  The input is operational:
the chosen degree-one parameters are a regular sequence in the coordinate ring, their quotient
is Artinian, and multiplication on the degree-one reduction is a perfect pairing into its
one-dimensional degree-two socle.  In particular, none of the proof-only Hilbert, exact-sequence,
or parameter-product certificates occurs in the public rank theorem below.

The Hilbert-series equation is deliberately a separate hypothesis, as it is in Theorem 1.1.
The implementation converts the native hypotheses to the older internal interfaces only inside
the proof.
-/

noncomputable section

universe u v w

open PowerSeries DirectSum

namespace DelPezzoBlekherman

open ArtinianGorensteinDegreeOneCertificate

variable {K : Type u} {A : Type v}
variable [Field K] [CommRing A] [Algebra K A]

/-- The ideal generated by a chosen tuple of homogeneous degree-one parameters. -/
def degreeOneParameterIdeal
    (𝒜 : ℕ → Submodule K A) {n : ℕ} (parameters : Fin n → 𝒜 1) : Ideal A :=
  Ideal.span (Set.range fun i ↦ (parameters i : A))

/-- An ideal generated by homogeneous degree-one parameters is homogeneous.  This is the first
native ingredient needed to grade the actual Artinian parameter quotient, rather than supplying
its homogeneous pieces as an external certificate. -/
theorem degreeOneParameterIdeal_isHomogeneous
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    {n : ℕ} (parameters : Fin n → 𝒜 1) :
    (degreeOneParameterIdeal 𝒜 parameters).IsHomogeneous 𝒜 := by
  apply Ideal.homogeneous_span
  rintro x ⟨i, rfl⟩
  exact SetLike.isHomogeneousElem_coe (parameters i)

/-- The ideal generated by the first `i` members of a chosen tuple of degree-one parameters.
This is the concrete chain of ideals used to iterate the one-parameter exact sequence. -/
def degreeOneParameterPrefixIdeal
    (𝒜 : ℕ → Submodule K A) {n : ℕ} (parameters : Fin n → 𝒜 1) (i : ℕ) : Ideal A :=
  Ideal.ofList ((List.ofFn fun j ↦ (parameters j : A)).take i)

/-- Every prefix ideal of a homogeneous degree-one parameter tuple is homogeneous. -/
theorem degreeOneParameterPrefixIdeal_isHomogeneous
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    {n : ℕ} (parameters : Fin n → 𝒜 1) (i : ℕ) :
    (degreeOneParameterPrefixIdeal 𝒜 parameters i).IsHomogeneous 𝒜 := by
  apply Ideal.homogeneous_span
  intro a ha
  change a ∈ (List.ofFn fun j ↦ (parameters j : A)).take i at ha
  have ha' : a ∈ List.ofFn (fun j ↦ (parameters j : A)) := List.mem_of_mem_take ha
  rw [List.mem_ofFn'] at ha'
  obtain ⟨j, rfl⟩ := ha'
  exact SetLike.isHomogeneousElem_coe (parameters j)

/-- Passing from one prefix ideal to the next adjoins precisely the next parameter. -/
theorem degreeOneParameterPrefixIdeal_succ
    (𝒜 : ℕ → Submodule K A)
    {n : ℕ} (parameters : Fin n → 𝒜 1) (i : ℕ) (hi : i < n) :
    degreeOneParameterPrefixIdeal 𝒜 parameters (i + 1) =
      degreeOneParameterPrefixIdeal 𝒜 parameters i ⊔
        Ideal.span {((parameters ⟨i, hi⟩ : 𝒜 1) : A)} := by
  unfold degreeOneParameterPrefixIdeal
  rw [List.take_add_one, Ideal.ofList_append]
  have hilength : i < (List.ofFn fun j ↦ (parameters j : A)).length := by
    simpa using hi
  rw [List.getElem?_eq_getElem hilength, Option.toList_some,
    List.getElem_ofFn, Ideal.ofList_singleton]

/-- Mathlib regularity of the whole parameter sequence gives regularity of the next parameter
on the quotient by the concrete prefix ideal. -/
theorem degreeOneParameterPrefix_isSMulRegular
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    {n : ℕ} (parameters : Fin n → 𝒜 1)
    (hregular : RingTheory.Sequence.IsRegular A
      (List.ofFn fun j ↦ (parameters j : A)))
    (i : ℕ) (hi : i < n) :
    IsSMulRegular
      (A ⧸ (degreeOneParameterPrefixIdeal 𝒜 parameters i : Submodule A A))
      (parameters ⟨i, hi⟩ : A) := by
  have h := hregular.toIsWeaklyRegular.regular_mod_prev i (by simpa using hi)
  have hsmul :
      (Ideal.ofList ((List.ofFn fun j ↦ (parameters j : A)).take i) •
          (⊤ : Submodule A A)) =
        (Ideal.ofList ((List.ofFn fun j ↦ (parameters j : A)).take i) :
          Submodule A A) := by
    apply le_antisymm
    · rw [Submodule.smul_le]
      intro r hr a _
      simpa [smul_eq_mul, mul_comm] using
        (Ideal.mul_mem_left
          (Ideal.ofList ((List.ofFn fun j ↦ (parameters j : A)).take i)) a hr)
    · intro a ha
      rw [← mul_one a, ← smul_eq_mul]
      exact Submodule.smul_mem_smul ha Submodule.mem_top
  rw [hsmul] at h
  change IsSMulRegular
    (A ⧸ (Ideal.ofList ((List.ofFn fun j ↦ (parameters j : A)).take i) :
      Submodule A A)) (parameters ⟨i, hi⟩ : A)
  simpa only [List.getElem_ofFn] using h

/-- The degree-`d` part of an ideal, viewed inside the degree-`d` homogeneous component. -/
def idealComponent
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ) : Submodule K (𝒜 d) :=
  (I.restrictScalars K).comap (𝒜 d).subtype

/-- The concrete degree-`d` vector space of the quotient by an ideal.  When the ideal is
homogeneous, these spaces are the homogeneous components of the quotient grading. -/
abbrev idealQuotientComponent
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ) :=
  (𝒜 d) ⧸ idealComponent 𝒜 I d

/-- The additive quotient map restricted to one homogeneous component.  Its codomain is the
underlying `K`-module quotient by the ideal; this is definitionally the additive quotient used by
the ring quotient, while making the linear structure explicit. -/
def componentQuotientMap
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ) :
    𝒜 d →ₗ[K] (A ⧸ I.restrictScalars K) :=
  (I.restrictScalars K).mkQ.comp (𝒜 d).subtype

@[simp]
theorem componentQuotientMap_ker
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ) :
    LinearMap.ker (componentQuotientMap 𝒜 I d) = idealComponent 𝒜 I d := by
  ext x
  simp [componentQuotientMap, idealComponent]

/-- A degreewise quotient component is canonically the image of that component in the actual
ring quotient.  This connects the finite-dimensional Hilbert calculation to the operational
Artinian quotient in `IsArithmeticallyGorenstein`. -/
noncomputable def idealQuotientComponentEquivRange
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ) :
    idealQuotientComponent 𝒜 I d ≃ₗ[K] LinearMap.range (componentQuotientMap 𝒜 I d) :=
  (Submodule.quotEquivOfEq _ _ (componentQuotientMap_ker 𝒜 I d).symm).trans
    (componentQuotientMap 𝒜 I d).quotKerEquivRange

/-- Finite-dimensional homogeneous pieces give finite-dimensional quotient pieces. -/
theorem moduleFinite_idealQuotientComponent
    (𝒜 : ℕ → Submodule K A) (I : Ideal A) (d : ℕ)
    [Module.Finite K (𝒜 d)] :
    Module.Finite K (idealQuotientComponent 𝒜 I d) := by
  infer_instance

/-- Decompose the ambient graded ring and quotient every homogeneous component. -/
def idealQuotientDecompositionMap
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜] (I : Ideal A) :
    A →ₗ[K] ⨁ d, idealQuotientComponent 𝒜 I d :=
  (DirectSum.lmap fun d ↦ (idealComponent 𝒜 I d).mkQ).comp
    (DirectSum.decomposeLinearEquiv 𝒜).toLinearMap

theorem idealQuotientDecompositionMap_surjective
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜] (I : Ideal A) :
    Function.Surjective (idealQuotientDecompositionMap 𝒜 I) := by
  unfold idealQuotientDecompositionMap
  have hlmap : Function.Surjective
      (DirectSum.lmap fun d ↦ (idealComponent 𝒜 I d).mkQ) := by
    rw [DirectSum.lmap_surjective]
    intro d
    exact Submodule.mkQ_surjective _
  exact hlmap.comp (DirectSum.decomposeLinearEquiv 𝒜).surjective

/-- For a homogeneous ideal, the kernel of componentwise quotienting is the ideal itself. -/
theorem idealQuotientDecompositionMap_ker
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜] (I : Ideal A)
    (hI : I.IsHomogeneous 𝒜) :
    LinearMap.ker (idealQuotientDecompositionMap 𝒜 I) = I.restrictScalars K := by
  ext a
  rw [LinearMap.mem_ker]
  constructor
  · intro ha
    change a ∈ I
    rw [Ideal.IsHomogeneous.mem_iff 𝒜 hI]
    intro d
    have hd := congrArg (fun z ↦ z d) ha
    have hd' : (idealComponent 𝒜 I d).mkQ (DirectSum.decompose 𝒜 a d) = 0 := by
      simpa [idealQuotientDecompositionMap, LinearMap.comp_apply,
        DirectSum.decomposeLinearEquiv_apply] using hd
    have hdmem : DirectSum.decompose 𝒜 a d ∈ idealComponent 𝒜 I d := by
      simpa using hd'
    exact hdmem
  · intro ha
    apply DirectSum.ext
    intro d
    rw [show idealQuotientDecompositionMap 𝒜 I a =
        DirectSum.lmap (fun d ↦ (idealComponent 𝒜 I d).mkQ)
          ((DirectSum.decomposeLinearEquiv 𝒜) a) by rfl,
      DirectSum.lmap_apply]
    simp only [DirectSum.decomposeLinearEquiv_apply]
    change (idealComponent 𝒜 I d).mkQ (DirectSum.decompose 𝒜 a d) = 0
    apply (Submodule.Quotient.mk_eq_zero (idealComponent 𝒜 I d)).2
    exact (Ideal.IsHomogeneous.mem_iff 𝒜 hI).mp ha d

variable (K) in
/-- Restrict an infinite direct sum to its first `n` components. -/
def directSumTruncate
    (n : ℕ) (Q : ℕ → Type w)
    [(d : ℕ) → AddCommGroup (Q d)] [(d : ℕ) → Module K (Q d)] :
    (⨁ d : ℕ, Q d) →ₗ[K] ⨁ i : Fin n, Q i :=
  DirectSum.toModule K ℕ _ fun d ↦
    if hd : d < n then DirectSum.lof K (Fin n) (fun i ↦ Q i) ⟨d, hd⟩ else 0

variable (K) in
/-- Include a finite initial direct sum in the full direct sum. -/
def directSumInclude
    (n : ℕ) (Q : ℕ → Type w)
    [(d : ℕ) → AddCommGroup (Q d)] [(d : ℕ) → Module K (Q d)] :
    (⨁ i : Fin n, Q i) →ₗ[K] ⨁ d : ℕ, Q d :=
  DirectSum.toModule K (Fin n) _ fun i ↦ DirectSum.lof K ℕ Q i

theorem directSumTruncate_comp_include
    (n : ℕ) (Q : ℕ → Type w)
    [(d : ℕ) → AddCommGroup (Q d)] [(d : ℕ) → Module K (Q d)] :
    (directSumTruncate K n Q).comp (directSumInclude K n Q) = LinearMap.id := by
  apply DirectSum.linearMap_ext
  intro i
  ext x
  simp [directSumTruncate, directSumInclude, i.isLt]

theorem directSumInclude_comp_truncate
    (n : ℕ) (Q : ℕ → Type w)
    [(d : ℕ) → AddCommGroup (Q d)] [(d : ℕ) → Module K (Q d)]
    (hzero : ∀ d, n ≤ d → Subsingleton (Q d)) :
    (directSumInclude K n Q).comp (directSumTruncate K n Q) = LinearMap.id := by
  apply DirectSum.linearMap_ext
  intro d
  ext x
  by_cases hd : d < n
  · simp [directSumTruncate, directSumInclude, hd]
  · haveI : Subsingleton (Q d) := hzero d (Nat.le_of_not_gt hd)
    have hx : x = 0 := Subsingleton.elim _ _
    simp [hx]

/-- An infinite direct sum whose components vanish from `n` onward is its finite initial direct
sum. -/
noncomputable def directSumTruncationEquiv
    (n : ℕ) (Q : ℕ → Type w)
    [(d : ℕ) → AddCommGroup (Q d)] [(d : ℕ) → Module K (Q d)]
    (hzero : ∀ d, n ≤ d → Subsingleton (Q d)) :
    (⨁ d : ℕ, Q d) ≃ₗ[K] ⨁ i : Fin n, Q i :=
  LinearEquiv.ofLinear (directSumTruncate K n Q) (directSumInclude K n Q)
    (directSumTruncate_comp_include n Q)
    (directSumInclude_comp_truncate n Q hzero)

/-- Finrank of an eventually-zero direct sum is the sum of the initial component finranks. -/
theorem finrank_directSum_eq_sum_fin
    (n : ℕ) (Q : ℕ → Type w)
    [(d : ℕ) → AddCommGroup (Q d)] [(d : ℕ) → Module K (Q d)]
    [(d : ℕ) → Module.Finite K (Q d)]
    (hzero : ∀ d, n ≤ d → Subsingleton (Q d)) :
    Module.finrank K (⨁ d : ℕ, Q d) =
      ∑ i : Fin n, Module.finrank K (Q i) := by
  let e := directSumTruncationEquiv (K := K) n Q hzero
  letI (i : Fin n) : Module.Finite K (Q i) := inferInstance
  letI : Module.Finite K (⨁ i : Fin n, Q i) := by infer_instance
  letI : Module.Finite K (⨁ d : ℕ, Q d) := Module.Finite.equiv e.symm
  calc
    Module.finrank K (⨁ d : ℕ, Q d) =
        Module.finrank K (⨁ i : Fin n, Q i) := e.finrank_eq
    _ = ∑ i : Fin n, Module.finrank K (Q i) :=
      Module.finrank_directSum K (fun i : Fin n ↦ Q i)

/-- Projection to the initial components of an eventually-zero direct sum is injective. -/
theorem directSumTruncate_injective
    (n : ℕ) (Q : ℕ → Type w)
    [(d : ℕ) → AddCommGroup (Q d)] [(d : ℕ) → Module K (Q d)]
    (hzero : ∀ d, n ≤ d → Subsingleton (Q d)) :
    Function.Injective (directSumTruncate K n Q) := by
  intro x y hxy
  have hx := LinearMap.congr_fun (directSumInclude_comp_truncate (K := K) n Q hzero) x
  have hy := LinearMap.congr_fun (directSumInclude_comp_truncate (K := K) n Q hzero) y
  change directSumInclude K n Q (directSumTruncate K n Q x) = x at hx
  change directSumInclude K n Q (directSumTruncate K n Q y) = y at hy
  rw [← hx, ← hy, hxy]

/-- Projection to a finite initial direct sum is always surjective. -/
theorem directSumTruncate_surjective
    (n : ℕ) (Q : ℕ → Type w)
    [(d : ℕ) → AddCommGroup (Q d)] [(d : ℕ) → Module K (Q d)] :
    Function.Surjective (directSumTruncate K n Q) := by
  intro y
  refine ⟨directSumInclude K n Q y, ?_⟩
  exact LinearMap.congr_fun (directSumTruncate_comp_include (K := K) n Q) y

/-- The actual quotient map, resolved into its first `n` homogeneous pieces. -/
noncomputable def idealQuotientFiniteDecompositionMap
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜] (I : Ideal A) (n : ℕ) :
    A →ₗ[K] ⨁ i : Fin n, idealQuotientComponent 𝒜 I i :=
  (directSumTruncate K n (fun d ↦ idealQuotientComponent 𝒜 I d)).comp
    (idealQuotientDecompositionMap 𝒜 I)

theorem idealQuotientFiniteDecompositionMap_surjective
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜] (I : Ideal A) (n : ℕ) :
    Function.Surjective (idealQuotientFiniteDecompositionMap 𝒜 I n) :=
  (directSumTruncate_surjective (K := K) n
    (fun d ↦ idealQuotientComponent 𝒜 I d)).comp
      (idealQuotientDecompositionMap_surjective 𝒜 I)

theorem idealQuotientFiniteDecompositionMap_ker
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜] (I : Ideal A)
    (hI : I.IsHomogeneous 𝒜) (n : ℕ)
    (hzero : ∀ d, n ≤ d → Subsingleton (idealQuotientComponent 𝒜 I d)) :
    LinearMap.ker (idealQuotientFiniteDecompositionMap 𝒜 I n) =
      I.restrictScalars K := by
  ext a
  rw [LinearMap.mem_ker]
  constructor
  · intro ha
    have ht : directSumTruncate K n (fun d ↦ idealQuotientComponent 𝒜 I d)
        (idealQuotientDecompositionMap 𝒜 I a) = 0 := by
      simpa [idealQuotientFiniteDecompositionMap, LinearMap.comp_apply] using ha
    have hall : idealQuotientDecompositionMap 𝒜 I a = 0 :=
      (directSumTruncate_injective (K := K) n
        (fun d ↦ idealQuotientComponent 𝒜 I d) hzero) (by simpa using ht)
    rw [← idealQuotientDecompositionMap_ker 𝒜 I hI, LinearMap.mem_ker]
    exact hall
  · intro ha
    change directSumTruncate K n (fun d ↦ idealQuotientComponent 𝒜 I d)
        (idealQuotientDecompositionMap 𝒜 I a) = 0
    rw [show idealQuotientDecompositionMap 𝒜 I a = 0 by
      apply LinearMap.mem_ker.mp
      rw [idealQuotientDecompositionMap_ker 𝒜 I hI]
      exact ha]
    rw [map_zero]

/-- A surjective linear map identifies the dimension of its kernel quotient with that of its
codomain. Kept as a small opaque interface to avoid re-elaborating the first isomorphism theorem
through large concrete graded-module types. -/
theorem finrank_quotient_ker_eq_of_surjective
    {M N : Type*} [AddCommGroup M] [AddCommGroup N] [Module K M] [Module K N]
    (f : M →ₗ[K] N) (hf : Function.Surjective f) :
    Module.finrank K (M ⧸ LinearMap.ker f) = Module.finrank K N :=
  (f.quotKerEquivOfSurjective hf).finrank_eq

/-- Dimension formula for a quotient presented as a finite direct sum. -/
theorem finrank_quotient_eq_sum_of_surjective_ker
    {M : Type*} [AddCommGroup M] [Module K M]
    {ι : Type*} [Fintype ι]
    (Q : ι → Type*) [(i : ι) → AddCommGroup (Q i)] [(i : ι) → Module K (Q i)]
    [(i : ι) → Module.Finite K (Q i)]
    (S : Submodule K M) (f : M →ₗ[K] ⨁ i, Q i)
    (hf : Function.Surjective f) (hker : LinearMap.ker f = S) :
    Module.finrank K (M ⧸ S) = ∑ i, Module.finrank K (Q i) := by
  rw [← hker, finrank_quotient_ker_eq_of_surjective f hf]
  exact Module.finrank_directSum K Q

/-- A homogeneous quotient supported below `n` has total dimension equal to the sum of the
dimensions of its first `n` concrete graded pieces. -/
theorem idealQuotient_finrank_eq_sum_fin
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜] (I : Ideal A)
    (hI : I.IsHomogeneous 𝒜) (n : ℕ)
    [(d : ℕ) → Module.Finite K (idealQuotientComponent 𝒜 I d)]
    (hzero : ∀ d, n ≤ d → Subsingleton (idealQuotientComponent 𝒜 I d)) :
    Module.finrank K (A ⧸ I.restrictScalars K) =
      ∑ i : Fin n, Module.finrank K (idealQuotientComponent 𝒜 I i) := by
  let f : A →ₗ[K] (⨁ i : Fin n, idealQuotientComponent 𝒜 I i) :=
    idealQuotientFiniteDecompositionMap 𝒜 I n
  have hf : Function.Surjective f := idealQuotientFiniteDecompositionMap_surjective 𝒜 I n
  have hker : LinearMap.ker f = I.restrictScalars K :=
    idealQuotientFiniteDecompositionMap_ker 𝒜 I hI n hzero
  exact finrank_quotient_eq_sum_of_surjective_ker
    (fun i : Fin n ↦ idealQuotientComponent 𝒜 I i)
    (I.restrictScalars K) f hf hker

/-- Multiplication by a fixed homogeneous element, between the corresponding homogeneous
components. -/
def gradedLeftMultiplication
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    {e : ℕ} (x : 𝒜 e) (d : ℕ) : 𝒜 d →ₗ[K] 𝒜 (e + d) where
  toFun y := ⟨(x : A) * (y : A), SetLike.mul_mem_graded x.2 y.2⟩
  map_add' y z := by
    apply Subtype.ext
    exact mul_add _ _ _
  map_smul' r y := by
    apply Subtype.ext
    simp

@[simp]
theorem gradedLeftMultiplication_apply
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    {e : ℕ} (x : 𝒜 e) (d : ℕ) (y : 𝒜 d) :
    ((gradedLeftMultiplication 𝒜 x d y : 𝒜 (e + d)) : A) = (x : A) * (y : A) :=
  rfl

/-- Multiplication preserves the degreewise part of every ideal. -/
theorem idealComponent_le_comap_gradedLeftMultiplication
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (I : Ideal A) {e : ℕ} (x : 𝒜 e) (d : ℕ) :
    idealComponent 𝒜 I d ≤
      (idealComponent 𝒜 I (e + d)).comap (gradedLeftMultiplication 𝒜 x d) := by
  intro y hy
  exact I.mul_mem_left (x : A) hy

/-- Multiplication by a homogeneous element on the actual degreewise ideal quotients.  For a
degree-one regular parameter this is the left-hand map in the desired Hilbert-function exact
sequence. -/
def idealQuotientComponentMul
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (I : Ideal A) {e : ℕ} (x : 𝒜 e) (d : ℕ) :
    idealQuotientComponent 𝒜 I d →ₗ[K] idealQuotientComponent 𝒜 I (e + d) :=
  (idealComponent 𝒜 I d).mapQ (idealComponent 𝒜 I (e + d))
    (gradedLeftMultiplication 𝒜 x d)
    (idealComponent_le_comap_gradedLeftMultiplication 𝒜 I x d)

@[simp]
theorem idealQuotientComponentMul_mk
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (I : Ideal A) {e : ℕ} (x : 𝒜 e) (d : ℕ) (y : 𝒜 d) :
    idealQuotientComponentMul 𝒜 I x d (Submodule.Quotient.mk y) =
      Submodule.Quotient.mk (gradedLeftMultiplication 𝒜 x d y) := by
  rfl

/-- Ring-theoretic regularity on the full ideal quotient implies injectivity of multiplication
on every homogeneous quotient component.  This discharges the injectivity field of the old
degreewise exact-sequence interface directly from native regularity. -/
theorem idealQuotientComponentMul_injective_of_isSMulRegular
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (I : Ideal A) {e : ℕ} (x : 𝒜 e) (d : ℕ)
    (hregular : IsSMulRegular (A ⧸ (I : Submodule A A)) (x : A)) :
    Function.Injective (idealQuotientComponentMul 𝒜 I x d) := by
  apply (injective_iff_map_eq_zero _).2
  intro q hq
  induction q using Submodule.Quotient.induction_on with
  | _ y =>
      rw [idealQuotientComponentMul_mk, Submodule.Quotient.mk_eq_zero] at hq
      rw [Submodule.Quotient.mk_eq_zero]
      exact mem_of_isSMulRegular_quotient_of_smul_mem hregular hq

/-- Inclusion of ideals induces inclusion of their degreewise components. -/
theorem idealComponent_mono
    (𝒜 : ℕ → Submodule K A) {I J : Ideal A} (hIJ : I ≤ J) (d : ℕ) :
    idealComponent 𝒜 I d ≤ idealComponent 𝒜 J d :=
  fun _ hy ↦ hIJ hy

/-- The canonical map on degreewise quotients induced by enlarging an ideal. -/
def idealQuotientComponentMapOfLE
    (𝒜 : ℕ → Submodule K A) {I J : Ideal A} (hIJ : I ≤ J) (d : ℕ) :
    idealQuotientComponent 𝒜 I d →ₗ[K] idealQuotientComponent 𝒜 J d :=
  (idealComponent 𝒜 I d).mapQ (idealComponent 𝒜 J d) LinearMap.id
    (by simpa using idealComponent_mono 𝒜 hIJ d)

@[simp]
theorem idealQuotientComponentMapOfLE_mk
    (𝒜 : ℕ → Submodule K A) {I J : Ideal A} (hIJ : I ≤ J) (d : ℕ)
    (y : 𝒜 d) :
    idealQuotientComponentMapOfLE 𝒜 hIJ d (Submodule.Quotient.mk y) =
      Submodule.Quotient.mk y := by
  rfl

/-- Enlarging an ideal gives a surjection on every degreewise quotient component. -/
theorem idealQuotientComponentMapOfLE_surjective
    (𝒜 : ℕ → Submodule K A) {I J : Ideal A} (hIJ : I ≤ J) (d : ℕ) :
    Function.Surjective (idealQuotientComponentMapOfLE 𝒜 hIJ d) := by
  intro q
  induction q using Submodule.Quotient.induction_on with
  | _ y => exact ⟨Submodule.Quotient.mk y, rfl⟩

/-- If the homogeneous multiplier belongs to the enlarged ideal, multiplication followed by
the quotient transition is zero.  This is the complex condition for the degreewise reduction
sequence; exactness will amount to the converse kernel inclusion. -/
theorem idealQuotientComponentMapOfLE_comp_mul_eq_zero
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    {I J : Ideal A} (hIJ : I ≤ J) {e : ℕ} (x : 𝒜 e) (hxJ : (x : A) ∈ J) (d : ℕ) :
    (idealQuotientComponentMapOfLE 𝒜 hIJ (e + d)).comp
        (idealQuotientComponentMul 𝒜 I x d) = 0 := by
  apply LinearMap.ext
  intro q
  induction q using Submodule.Quotient.induction_on with
  | _ y =>
      rw [LinearMap.comp_apply, idealQuotientComponentMul_mk,
        idealQuotientComponentMapOfLE_mk, LinearMap.zero_apply]
      rw [Submodule.Quotient.mk_eq_zero]
      exact J.mul_mem_right (y : A) hxJ

/-- For the ideal obtained by adjoining one homogeneous element, every class killed by the
transition to the enlarged quotient comes from multiplication by that element.  Together with
`idealQuotientComponentMapOfLE_comp_mul_eq_zero`, this is the exactness statement underlying
the degree-one Hilbert-function recurrence. -/
theorem idealQuotientComponentMapOfLE_ker_le_range_sup_span_singleton
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜)
    {e : ℕ} (x : 𝒜 e) (d : ℕ) :
    LinearMap.ker
        (idealQuotientComponentMapOfLE 𝒜
          (show I ≤ I ⊔ Ideal.span {(x : A)} from le_sup_left) (e + d)) ≤
      LinearMap.range (idealQuotientComponentMul 𝒜 I x d) := by
  intro q hq
  induction q using Submodule.Quotient.induction_on with
  | _ y =>
      rw [LinearMap.mem_ker, idealQuotientComponentMapOfLE_mk,
        Submodule.Quotient.mk_eq_zero] at hq
      change (y : A) ∈ I ⊔ Ideal.span {(x : A)} at hq
      rw [sup_comm, Ideal.mem_span_singleton_sup] at hq
      obtain ⟨a, b, hbI, haby⟩ := hq
      let a_d : 𝒜 d := DirectSum.decompose 𝒜 a d
      refine ⟨Submodule.Quotient.mk a_d, ?_⟩
      rw [idealQuotientComponentMul_mk]
      apply (Submodule.Quotient.eq _).mpr
      change (x : A) * (a_d : A) - (y : A) ∈ I
      have hbcomp : (DirectSum.decompose 𝒜 b (e + d) : A) ∈ I := hI _ hbI
      have hdecomp := congrArg (GradedRing.proj 𝒜 (e + d)) haby
      rw [map_add] at hdecomp
      simp only [GradedRing.proj_apply] at hdecomp
      have hax : (DirectSum.decompose 𝒜 (a * (x : A)) (e + d) : A) =
          (a_d : A) * (x : A) := by
        have hed : e + d - e = d := by omega
        have hraw :=
          DirectSum.coe_decompose_mul_of_right_mem_of_le (𝒜 := 𝒜) (n := e + d)
            (a := a) (b := (x : A)) x.2 (Nat.le_add_right e d)
        rw [hed] at hraw
        exact hraw
      have hy : (DirectSum.decompose 𝒜 (y : A) (e + d) : A) = (y : A) := by
        exact DirectSum.decompose_of_mem_same 𝒜 y.2
      rw [hax, hy] at hdecomp
      have hdiff : (y : A) - (x : A) * (a_d : A) ∈ I := by
        rw [mul_comm, ← hdecomp]
        simpa only [add_sub_cancel_left] using hbcomp
      simpa only [neg_sub] using I.neg_mem hdiff

/-- The degreewise sequence for quotienting by one homogeneous element is exact in its middle
term.  This result uses the actual ideals and quotient components, not a supplied exact-sequence
certificate. -/
theorem idealQuotientComponentMapOfLE_ker_eq_range_sup_span_singleton
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜)
    {e : ℕ} (x : 𝒜 e) (d : ℕ) :
    LinearMap.ker
        (idealQuotientComponentMapOfLE 𝒜
          (show I ≤ I ⊔ Ideal.span {(x : A)} from le_sup_left) (e + d)) =
      LinearMap.range (idealQuotientComponentMul 𝒜 I x d) := by
  apply le_antisymm
  · exact idealQuotientComponentMapOfLE_ker_le_range_sup_span_singleton 𝒜 I hI x d
  · rintro q ⟨p, rfl⟩
    rw [LinearMap.mem_ker]
    have hzero := congrArg (fun f => f p)
      (idealQuotientComponentMapOfLE_comp_mul_eq_zero 𝒜
        (show I ≤ I ⊔ Ideal.span {(x : A)} from le_sup_left) x
        (show (x : A) ∈ I ⊔ Ideal.span {(x : A)} from
          (show Ideal.span {(x : A)} ≤ I ⊔ Ideal.span {(x : A)} from le_sup_right)
            (Ideal.mem_span_singleton_self (x : A))) d)
    simpa using hzero

/-- Adjoining a positive-degree homogeneous element does not change the degree-zero quotient
component. -/
theorem idealComponent_zero_sup_span_degreeOne
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜)
    (x : 𝒜 1) :
    idealComponent 𝒜 I 0 = idealComponent 𝒜 (I ⊔ Ideal.span {(x : A)}) 0 := by
  apply le_antisymm
  · exact idealComponent_mono 𝒜 le_sup_left 0
  · intro y hy
    change (y : A) ∈ I
    change (y : A) ∈ I ⊔ Ideal.span {(x : A)} at hy
    rw [sup_comm, Ideal.mem_span_singleton_sup] at hy
    obtain ⟨a, b, hbI, haby⟩ := hy
    have hbcomp : (DirectSum.decompose 𝒜 b 0 : A) ∈ I := hI _ hbI
    have hdecomp := congrArg (GradedRing.proj 𝒜 0) haby
    rw [map_add] at hdecomp
    simp only [GradedRing.proj_apply] at hdecomp
    have hax : (DirectSum.decompose 𝒜 (a * (x : A)) 0 : A) = 0 := by
      exact DirectSum.coe_decompose_mul_of_right_mem_of_not_le
        (𝒜 := 𝒜) (a := a) (b := (x : A)) (i := 1) (n := 0) x.2 (by omega)
    have hy0 : (DirectSum.decompose 𝒜 (y : A) 0 : A) = (y : A) := by
      exact DirectSum.decompose_of_mem_same 𝒜 y.2
    rw [hax, zero_add, hy0] at hdecomp
    rw [← hdecomp]
    exact hbcomp

/-- The actual homogeneous ideal quotients by a degree-one nonzerodivisor satisfy the numerical
recurrence used in the Hilbert-series argument.  This packages the native exactness proof into
the existing arithmetic interface without asking a caller for any reduction certificate. -/
theorem idealQuotientComponent_finrankRelation
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜)
    (x : 𝒜 1)
    (hregular : IsSMulRegular (A ⧸ (I : Submodule A A)) (x : A))
    (hfinite : ∀ d, Module.Finite K (𝒜 d)) :
    DegreeOneReductionFinrankRelation
      (fun d => Module.finrank K (idealQuotientComponent 𝒜 I d))
      (fun d => Module.finrank K
        (idealQuotientComponent 𝒜 (I ⊔ Ideal.span {(x : A)}) d)) := by
  letI (d : ℕ) : Module.Finite K (𝒜 d) := hfinite d
  refine ⟨?_, fun d => ?_⟩
  · exact (Submodule.quotEquivOfEq _ _
      (idealComponent_zero_sup_span_degreeOne 𝒜 I hI x)).finrank_eq.symm
  · let mul := idealQuotientComponentMul 𝒜 I x d
    let transition := idealQuotientComponentMapOfLE 𝒜
      (show I ≤ I ⊔ Ideal.span {(x : A)} from le_sup_left) (1 + d)
    have hmul : Function.Injective mul :=
      idealQuotientComponentMul_injective_of_isSMulRegular 𝒜 I x d hregular
    have hsurj : Function.Surjective transition :=
      idealQuotientComponentMapOfLE_surjective 𝒜 le_sup_left (1 + d)
    have hexact : LinearMap.ker transition = LinearMap.range mul :=
      idealQuotientComponentMapOfLE_ker_eq_range_sup_span_singleton 𝒜 I hI x d
    let eCoker :
        (idealQuotientComponent 𝒜 I (1 + d) ⧸ LinearMap.range mul) ≃ₗ[K]
          idealQuotientComponent 𝒜 (I ⊔ Ideal.span {(x : A)}) (1 + d) :=
      (Submodule.quotEquivOfEq _ _ hexact.symm).trans
        (transition.quotKerEquivOfSurjective hsurj)
    calc
      Module.finrank K
            (idealQuotientComponent 𝒜 (I ⊔ Ideal.span {(x : A)}) (d + 1)) +
          Module.finrank K (idealQuotientComponent 𝒜 I d) =
        Module.finrank K
            (idealQuotientComponent 𝒜 I (1 + d) ⧸ LinearMap.range mul) +
          Module.finrank K (LinearMap.range mul) := by
            rw [show d + 1 = 1 + d by omega, eCoker.finrank_eq,
              LinearMap.finrank_range_of_inj hmul]
      _ = Module.finrank K (idealQuotientComponent 𝒜 I (1 + d)) :=
        Submodule.finrank_quotient_add_finrank (LinearMap.range mul)
      _ = Module.finrank K (idealQuotientComponent 𝒜 I (d + 1)) :=
        congrArg (fun n => Module.finrank K (idealQuotientComponent 𝒜 I n))
          (Nat.add_comm 1 d)

/-- The empty prefix generates the zero ideal. -/
theorem degreeOneParameterPrefixIdeal_zero
    (𝒜 : ℕ → Submodule K A)
    {n : ℕ} (parameters : Fin n → 𝒜 1) :
    degreeOneParameterPrefixIdeal 𝒜 parameters 0 = ⊥ := by
  simp [degreeOneParameterPrefixIdeal]

/-- The full prefix is the ideal generated by the entire parameter tuple. -/
theorem degreeOneParameterPrefixIdeal_full
    (𝒜 : ℕ → Submodule K A)
    {n : ℕ} (parameters : Fin n → 𝒜 1) :
    degreeOneParameterPrefixIdeal 𝒜 parameters n =
      degreeOneParameterIdeal 𝒜 parameters := by
  unfold degreeOneParameterPrefixIdeal degreeOneParameterIdeal
  rw [show (List.ofFn fun j ↦ (parameters j : A)).take n =
      List.ofFn (fun j ↦ (parameters j : A)) by simp]
  apply congrArg Ideal.span
  ext a
  change a ∈ List.ofFn (fun j ↦ (parameters j : A)) ↔
    a ∈ Set.range (fun j ↦ (parameters j : A))
  exact List.mem_ofFn' (fun j ↦ (parameters j : A)) a

/-- A regular tuple of degree-one parameters constructs all numerical Hilbert-function
recurrences for its actual chain of prefix ideals.  No exact-sequence certificate is supplied
by the caller. -/
theorem degreeOneParameterPrefix_finrankRelations
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    {n : ℕ} (parameters : Fin n → 𝒜 1)
    (hregular : RingTheory.Sequence.IsRegular A
      (List.ofFn fun j ↦ (parameters j : A)))
    (hfinite : ∀ d, Module.Finite K (𝒜 d)) :
    SuccessiveLinearReductionFinrankRelations
      (fun i d ↦ Module.finrank K
        (idealQuotientComponent 𝒜
          (degreeOneParameterPrefixIdeal 𝒜 parameters i) d)) n := by
  refine ⟨fun i hi ↦ ?_⟩
  have hrelation := idealQuotientComponent_finrankRelation 𝒜
    (degreeOneParameterPrefixIdeal 𝒜 parameters i)
    (degreeOneParameterPrefixIdeal_isHomogeneous 𝒜 parameters i)
    (parameters ⟨i, hi⟩)
    (degreeOneParameterPrefix_isSMulRegular 𝒜 parameters hregular i hi)
    hfinite
  rw [← degreeOneParameterPrefixIdeal_succ 𝒜 parameters i hi] at hrelation
  exact hrelation

/-- Quotienting a homogeneous component by the degreewise part of the zero ideal recovers the
component itself. -/
noncomputable def idealQuotientComponentBotEquiv
    (𝒜 : ℕ → Submodule K A) (d : ℕ) :
    idealQuotientComponent 𝒜 (⊥ : Ideal A) d ≃ₗ[K] 𝒜 d :=
  Submodule.quotEquivOfEqBot _ (by
    ext x
    simp [idealComponent])

/-- A regular `(m+1)`-tuple of actual degree-one parameters cancels the denominator in the
paper's Hilbert series.  Thus the concrete parameter-ideal quotient has degreewise Hilbert
function `(1,c,1)`.  This is the native Proposition 2.2 Hilbert bridge: its public signature
contains neither a Hilbert certificate nor supplied reduction exact sequences. -/
theorem degreeOneParameterIdeal_finrank_eq_delPezzoHilbertNumerator
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    {m c : ℕ} (parameters : Fin (m + 1) → 𝒜 1)
    (hregular : RingTheory.Sequence.IsRegular A
      (List.ofFn fun j ↦ (parameters j : A)))
    (hfinite : ∀ d, Module.Finite K (𝒜 d))
    (hHilbert : ∀ d,
      (Module.finrank K (𝒜 d) : ℤ) = coeff d (delPezzoHilbertSeries m c)) :
    ∀ d,
      (Module.finrank K
        (idealQuotientComponent 𝒜 (degreeOneParameterIdeal 𝒜 parameters) d) : ℤ) =
        coeff d (delPezzoHilbertNumerator c) := by
  let hfun : ℕ → ℕ → ℕ := fun i d ↦ Module.finrank K
    (idealQuotientComponent 𝒜
      (degreeOneParameterPrefixIdeal 𝒜 parameters i) d)
  have hrelations : SuccessiveLinearReductionFinrankRelations hfun (m + 1) :=
    degreeOneParameterPrefix_finrankRelations 𝒜 parameters hregular hfinite
  have hseries := hrelations.hilbertFunctionSeries_eq_mul_pow
  have hinitial : hilbertFunctionSeries (hfun 0) = delPezzoHilbertSeries m c := by
    ext d
    rw [coeff_hilbertFunctionSeries, ← hHilbert d]
    change (Module.finrank K
      (idealQuotientComponent 𝒜
        (degreeOneParameterPrefixIdeal 𝒜 parameters 0) d) : ℤ) = _
    rw [degreeOneParameterPrefixIdeal_zero]
    exact_mod_cast (idealQuotientComponentBotEquiv 𝒜 d).finrank_eq
  intro d
  rw [← delPezzoHilbertSeries_mul_one_sub_pow m c]
  calc
    (Module.finrank K
      (idealQuotientComponent 𝒜 (degreeOneParameterIdeal 𝒜 parameters) d) : ℤ) =
        coeff d (hilbertFunctionSeries (hfun (m + 1))) := by
          rw [coeff_hilbertFunctionSeries]
          change (_ : ℤ) = (Module.finrank K
            (idealQuotientComponent 𝒜
              (degreeOneParameterPrefixIdeal 𝒜 parameters (m + 1)) d) : ℤ)
          rw [degreeOneParameterPrefixIdeal_full]
    _ = coeff d (hilbertFunctionSeries (hfun 0) * (1 - X) ^ (m + 1)) :=
      congrArg (coeff d) hseries
    _ = coeff d (delPezzoHilbertSeries m c * (1 - X) ^ (m + 1)) := by
      rw [hinitial]

/-- The degree-one part of the actual regular parameter quotient has dimension `c`. -/
theorem degreeOneParameterIdeal_finrank_one
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    {m c : ℕ} (parameters : Fin (m + 1) → 𝒜 1)
    (hregular : RingTheory.Sequence.IsRegular A
      (List.ofFn fun j ↦ (parameters j : A)))
    (hfinite : ∀ d, Module.Finite K (𝒜 d))
    (hHilbert : ∀ d,
      (Module.finrank K (𝒜 d) : ℤ) = coeff d (delPezzoHilbertSeries m c)) :
    Module.finrank K
      (idealQuotientComponent 𝒜 (degreeOneParameterIdeal 𝒜 parameters) 1) = c := by
  have h := degreeOneParameterIdeal_finrank_eq_delPezzoHilbertNumerator
    𝒜 parameters hregular hfinite hHilbert 1
  rw [coeff_one_delPezzoHilbertNumerator] at h
  exact_mod_cast h

/-- The degree-two part of the actual regular parameter quotient is one-dimensional. -/
theorem degreeOneParameterIdeal_finrank_two
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    {m c : ℕ} (parameters : Fin (m + 1) → 𝒜 1)
    (hregular : RingTheory.Sequence.IsRegular A
      (List.ofFn fun j ↦ (parameters j : A)))
    (hfinite : ∀ d, Module.Finite K (𝒜 d))
    (hHilbert : ∀ d,
      (Module.finrank K (𝒜 d) : ℤ) = coeff d (delPezzoHilbertSeries m c)) :
    Module.finrank K
      (idealQuotientComponent 𝒜 (degreeOneParameterIdeal 𝒜 parameters) 2) = 1 := by
  have h := degreeOneParameterIdeal_finrank_eq_delPezzoHilbertNumerator
    𝒜 parameters hregular hfinite hHilbert 2
  rw [coeff_two_delPezzoHilbertNumerator] at h
  exact_mod_cast h

/-- Every component of the actual regular parameter quotient above degree two vanishes. -/
theorem degreeOneParameterIdeal_finrank_eq_zero_of_three_le
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    {m c : ℕ} (parameters : Fin (m + 1) → 𝒜 1)
    (hregular : RingTheory.Sequence.IsRegular A
      (List.ofFn fun j ↦ (parameters j : A)))
    (hfinite : ∀ d, Module.Finite K (𝒜 d))
    (hHilbert : ∀ d,
      (Module.finrank K (𝒜 d) : ℤ) = coeff d (delPezzoHilbertSeries m c))
    {d : ℕ} (hd : 3 ≤ d) :
    Module.finrank K
      (idealQuotientComponent 𝒜 (degreeOneParameterIdeal 𝒜 parameters) d) = 0 := by
  have h := degreeOneParameterIdeal_finrank_eq_delPezzoHilbertNumerator
    𝒜 parameters hregular hfinite hHilbert d
  rw [coeff_delPezzoHilbertNumerator_eq_zero_of_three_le c hd] at h
  exact_mod_cast h

set_option maxHeartbeats 500000 in
-- The calculation unfolds three finite graded quotient components during elaboration.
/-- The actual Artinian parameter quotient has total vector-space dimension `c + 2`.

This is the basis-free numerical content needed for the degree computation: it is derived from
the literal Hilbert series and regularity, not supplied as an `HVectorOneCOneFreeCertificate` or
as a chosen basis of the coordinate ring over the parameter polynomial ring. -/
theorem degreeOneParameterIdeal_quotient_finrank
    (𝒜 : ℕ → Submodule K A) [GradedRing 𝒜]
    {m c : ℕ} (parameters : Fin (m + 1) → 𝒜 1)
    (hregular : RingTheory.Sequence.IsRegular A
      (List.ofFn fun j ↦ (parameters j : A)))
    (hfinite : ∀ d, Module.Finite K (𝒜 d))
    (hHilbert : ∀ d,
      (Module.finrank K (𝒜 d) : ℤ) = coeff d (delPezzoHilbertSeries m c)) :
    Module.finrank K
      (A ⧸ (degreeOneParameterIdeal 𝒜 parameters).restrictScalars K) = c + 2 := by
  let I := degreeOneParameterIdeal 𝒜 parameters
  let Q : ℕ → Type v := fun d ↦ idealQuotientComponent 𝒜 I d
  letI (d : ℕ) : Module.Finite K (Q d) :=
    moduleFinite_idealQuotientComponent 𝒜 I d
  have hzero : ∀ d, 3 ≤ d → Subsingleton (Q d) := by
    intro d hd
    exact Module.finrank_zero_iff.mp
      (degreeOneParameterIdeal_finrank_eq_zero_of_three_le
        𝒜 parameters hregular hfinite hHilbert hd)
  letI (i : Fin 3) : Module.Finite K (Q i) := inferInstance
  calc
    Module.finrank K (A ⧸ I.restrictScalars K) =
        ∑ i : Fin 3, Module.finrank K (Q i) :=
      idealQuotient_finrank_eq_sum_fin 𝒜 I
        (degreeOneParameterIdeal_isHomogeneous 𝒜 parameters) 3 hzero
    _ = 1 + c + 1 := by
      rw [Fin.sum_univ_succ, Fin.sum_univ_succ, Fin.sum_univ_succ,
        Fin.sum_univ_zero]
      change Module.finrank K (idealQuotientComponent 𝒜 I 0) +
          (Module.finrank K (idealQuotientComponent 𝒜 I 1) +
          (Module.finrank K (idealQuotientComponent 𝒜 I 2) + 0)) = 1 + c + 1
      rw [show Module.finrank K (idealQuotientComponent 𝒜 I 0) = 1 by
          have h := degreeOneParameterIdeal_finrank_eq_delPezzoHilbertNumerator
            𝒜 parameters hregular hfinite hHilbert 0
          rw [coeff_zero_delPezzoHilbertNumerator] at h
          exact_mod_cast h,
        degreeOneParameterIdeal_finrank_one 𝒜 parameters hregular hfinite hHilbert,
        degreeOneParameterIdeal_finrank_two 𝒜 parameters hregular hfinite hHilbert]
      omega
    _ = c + 2 := by omega

/-- Operational form of the arithmetically Gorenstein hypothesis along the degree-one
parameters used in the proof.

* `regular` is mathlib's ring-theoretic regular-sequence predicate, applied to the actual
  homogeneous elements of the coordinate ring;
* `artinian` says that their ring quotient is the Artinian reduction;
* `socleFinrankOne` and `perfectSocleMultiplication` state the `(1,c,1)` Gorenstein conclusion
  on the concrete degree-one and degree-two component quotients.

This does not contain, extend, or mention any of the older project-specific bridge
certificates. -/
structure IsArithmeticallyGorenstein
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    {m : ℕ} (parameters : Fin (m + 1) → 𝒜 1) : Prop where
  regular : RingTheory.Sequence.IsRegular A
    (List.ofFn fun i ↦ (parameters i : A))
  artinian : IsArtinianRing (A ⧸ degreeOneParameterIdeal 𝒜 parameters)
  socleFinrankOne :
    Module.finrank K
      (𝒜 2 ⧸ parameterProductSubmodule
        (Submodule.span K (Set.range parameters))
        (gradedDegreeOneMultiplication 𝒜)) = 1
  perfectSocleMultiplication :
    (parameterProductQuotientMultiplication
      (Submodule.span K (Set.range parameters))
      (gradedDegreeOneMultiplication 𝒜)
      (gradedDegreeOneMultiplication_symmetric 𝒜)).Nondegenerate

/-- The literal Hilbert-series equation from the paper supplies finite-dimensionality of the
degree-one component.  The equation is kept unbundled in the statement so callers do not need
to manufacture `DelPezzoHilbertSeriesCertificate`. -/
theorem moduleFinite_degreeOne_of_delPezzoHilbertSeries
    (𝒜 : ℕ → Submodule K A) {m c : ℕ}
    (hHilbert : ∀ d,
      (Module.finrank K (𝒜 d) : ℤ) = coeff d (delPezzoHilbertSeries m c)) :
    Module.Finite K (𝒜 1) := by
  exact (DelPezzoHilbertSeriesCertificate.mk hHilbert).moduleFinite_one

/-- Native algebraic rank endpoint for the Theorem 4.3 step used in Theorem 1.1(ii).

The public assumptions are the actual graded coordinate-ring pieces, standard-graded
degree-two generation, a nonzero degree-two functional, the chosen regular degree-one
parameters, the literal Hilbert-series equation, and the operational arithmetically Gorenstein
property.  The conclusion identifies the actual Hankel kernel, proves that it has dimension
`m + 1`, and proves rank `c`.

In particular, the signature contains none of
`HVectorOneCOneFreeCertificate`, `DelPezzoHilbertSeriesCertificate`,
`SuccessiveDegreeOneReductionComponentExactSequences`, or
`ParameterProductGorensteinCertificate`. -/
theorem hankelKernel_eq_parameterSpan_and_rank_of_arithmeticallyGorenstein
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (hgenerated : DegreeTwoGeneratedByDegreeOne 𝒜)
    (ell : 𝒜 2 →ₗ[K] K) (hell : ell ≠ 0)
    {m c : ℕ}
    (parameters : Fin (m + 1) → 𝒜 1)
    (hparameters : LinearIndependent K parameters)
    (hparametersKernel : ∀ i,
      parameters i ∈ LinearMap.ker ((gradedDegreeOneMultiplication 𝒜).compr₂ ell))
    (hHilbert : ∀ d,
      (Module.finrank K (𝒜 d) : ℤ) = coeff d (delPezzoHilbertSeries m c))
    (hAG : IsArithmeticallyGorenstein 𝒜 parameters) :
    LinearMap.ker ((gradedDegreeOneMultiplication 𝒜).compr₂ ell) =
        Submodule.span K (Set.range parameters) ∧
      Module.finrank K
          (LinearMap.ker ((gradedDegreeOneMultiplication 𝒜).compr₂ ell)) = m + 1 ∧
      @LinearMap.BilinForm.finiteRank K (𝒜 1) _ _ _
        (moduleFinite_degreeOne_of_delPezzoHilbertSeries 𝒜 hHilbert)
        ((gradedDegreeOneMultiplication 𝒜).compr₂ ell) = c := by
  let hHilbertInternal : DelPezzoHilbertSeriesCertificate 𝒜 m c :=
    ⟨hHilbert⟩
  let hPairingInternal : ParameterProductPerfectPairingCertificate
      (Submodule.span K (Set.range parameters))
      (gradedDegreeOneMultiplication 𝒜)
      (gradedDegreeOneMultiplication_symmetric 𝒜) :=
    { socleFinrankOne := hAG.socleFinrankOne
      perfect := hAG.perfectSocleMultiplication }
  let _ : Module.Finite K (𝒜 1) :=
    moduleFinite_degreeOne_of_delPezzoHilbertSeries 𝒜 hHilbert
  have hR₁ : Module.finrank K (𝒜 1) = m + c + 1 := by
    simpa only [hilbertDegreeOne, add_assoc, add_comm, add_left_comm] using
      hHilbertInternal.finrank_one
  have hKernelRank := hankelKernel_eq_parameterSpan_and_rank_of_parameters_mem_hankelKernel
    (gradedDegreeOneMultiplication 𝒜)
    (gradedDegreeOneMultiplication_symmetric 𝒜) ell hell
    (symmetricSquare_gradedDegreeOneMultiplication_surjective 𝒜 hgenerated)
    parameters hparameters hparametersKernel hPairingInternal hR₁
  refine ⟨hKernelRank.1, ?_, hKernelRank.2⟩
  rw [hKernelRank.1, finrank_span_eq_card hparameters]
  simp

end DelPezzoBlekherman
