/-
Copyright (c) 2026 Codex. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import DelPezzoBlekherman.Algebra.QuotientMultiplication
import Mathlib.LinearAlgebra.TensorProduct.Submodule
import Mathlib.RingTheory.GradedAlgebra.Basic

/-!
# Standard-graded degree-two multiplication

This file connects the abstract quotient-pairing rank theorem to canonical multiplication of a
degree-one submodule inside a commutative algebra.
-/

noncomputable section

universe u v

open scoped TensorProduct

namespace ArtinianGorensteinDegreeOneCertificate

variable {K : Type u} {A : Type v}
variable [Field K] [CommRing A] [Algebra K A]

/-- Multiplication of a subspace `U` with itself, valued in the canonical product submodule
`U * U`.  This is the degree-one-to-degree-two multiplication of a standard graded algebra
when its degree-two piece is identified with the span of degree-one products. -/
def submoduleProductMultiplication (U : Submodule K A) :
    U →ₗ[K] U →ₗ[K] (U * U) :=
  (TensorProduct.lift.equiv (.id K) U U (U * U)).symm (Submodule.mulMap' U U)

@[simp]
theorem submoduleProductMultiplication_apply (U : Submodule K A) (x y : U) :
    ((submoduleProductMultiplication U x y : U * U) : A) = (x : A) * (y : A) := by
  simp [submoduleProductMultiplication]

/-- The bilinear map obtained from canonical submodule multiplication linearizes back to
mathlib's tensor multiplication map. -/
theorem tensorProduct_lift_submoduleProductMultiplication (U : Submodule K A) :
    TensorProduct.lift (submoduleProductMultiplication U) = Submodule.mulMap' U U := by
  exact (TensorProduct.lift.equiv (.id K) U U (U * U)).apply_symm_apply
    (Submodule.mulMap' U U)

/-- Canonical degree-one multiplication in a commutative algebra is symmetric. -/
theorem submoduleProductMultiplication_symmetric (U : Submodule K A) :
    ∀ x y, submoduleProductMultiplication U x y = submoduleProductMultiplication U y x := by
  intro x y
  apply Subtype.ext
  simp only [submoduleProductMultiplication_apply]
  exact mul_comm _ _

/-- The tensor-linearized canonical product multiplication is surjective onto `U * U`. -/
theorem tensorProduct_lift_submoduleProductMultiplication_surjective (U : Submodule K A) :
    Function.Surjective (TensorProduct.lift (submoduleProductMultiplication U)) := by
  rw [tensorProduct_lift_submoduleProductMultiplication]
  exact Submodule.mulMap'_surjective U U

/-- Consequently, the PDF's symmetric-square multiplication is automatically surjective onto
the canonical degree-two product submodule of a commutative algebra. -/
theorem symmetricSquare_submoduleProductMultiplication_surjective (U : Submodule K A) :
    Function.Surjective (symmetricSquareMultiplication
      (submoduleProductMultiplication U) (submoduleProductMultiplication_symmetric U)) :=
  symmetricSquareMultiplication_surjective_of_tensorProduct_lift_surjective
    (submoduleProductMultiplication U) (submoduleProductMultiplication_symmetric U)
    (tensorProduct_lift_submoduleProductMultiplication_surjective U)

/-- In an internal grading, products of degree-one elements lie in degree two. -/
theorem degreeOne_mul_self_le_degreeTwo
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜] :
    𝒜 1 * 𝒜 1 ≤ 𝒜 2 := by
  rw [Submodule.mul_le]
  intro x hx y hy
  simpa using SetLike.mul_mem_graded hx hy

/-- Canonical multiplication from the degree-one component to the degree-two component of an
internal grading. -/
def gradedDegreeOneMultiplication
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜] :
    𝒜 1 →ₗ[K] 𝒜 1 →ₗ[K] 𝒜 2 :=
  (submoduleProductMultiplication (𝒜 1)).compr₂
    (Submodule.inclusion (degreeOne_mul_self_le_degreeTwo 𝒜))

@[simp]
theorem gradedDegreeOneMultiplication_apply
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜] (x y : 𝒜 1) :
    ((gradedDegreeOneMultiplication 𝒜 x y : 𝒜 2) : A) = (x : A) * (y : A) := by
  simp [gradedDegreeOneMultiplication]

/-- The exact degree-two consequence of standard gradedness used in the PDF: degree two is
generated by products of degree-one elements. -/
def DegreeTwoGeneratedByDegreeOne
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜] : Prop :=
  Function.Surjective (TensorProduct.lift (gradedDegreeOneMultiplication 𝒜))

/-- The paper's degree-two generation hypothesis identifies the canonical product submodule
`R₁ * R₁` with the named homogeneous component `R₂`. -/
theorem degreeOne_mul_self_eq_degreeTwo
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (hgenerated : DegreeTwoGeneratedByDegreeOne 𝒜) :
    𝒜 1 * 𝒜 1 = 𝒜 2 := by
  let hle := degreeOne_mul_self_le_degreeTwo 𝒜
  have hcomp : Function.Surjective
      ((Submodule.inclusion hle) ∘ₗ (Submodule.mulMap' (𝒜 1) (𝒜 1))) := by
    simpa only [DegreeTwoGeneratedByDegreeOne, gradedDegreeOneMultiplication,
      TensorProduct.lift_compr₂, tensorProduct_lift_submoduleProductMultiplication]
      using hgenerated
  have hinclusion : Function.Surjective (Submodule.inclusion hle) := by
    exact Function.Surjective.of_comp hcomp
  apply SetLike.coe_injective
  exact Set.eq_of_inclusion_surjective (h := hle) hinclusion

/-- Degree-one multiplication in a commutative internally graded algebra is symmetric. -/
theorem gradedDegreeOneMultiplication_symmetric
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜] :
    ∀ x y, gradedDegreeOneMultiplication 𝒜 x y =
      gradedDegreeOneMultiplication 𝒜 y x := by
  intro x y
  apply Subtype.ext
  simp only [gradedDegreeOneMultiplication_apply]
  exact mul_comm _ _

/-- Degree-two generation by degree one is equivalent to surjectivity of the PDF's symmetric
square multiplication map in this internal-graded setting. -/
theorem symmetricSquare_gradedDegreeOneMultiplication_surjective
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (hgenerated : DegreeTwoGeneratedByDegreeOne 𝒜) :
    Function.Surjective (symmetricSquareMultiplication
      (gradedDegreeOneMultiplication 𝒜)
      (gradedDegreeOneMultiplication_symmetric 𝒜)) :=
  symmetricSquareMultiplication_surjective_of_tensorProduct_lift_surjective
    (gradedDegreeOneMultiplication 𝒜) (gradedDegreeOneMultiplication_symmetric 𝒜)
    hgenerated

/-- Canonical multiplication transported from `U * U` to a named degree-two submodule `Q`
identified with that product submodule. -/
def submoduleMultiplicationToDegreeTwo
    (U Q : Submodule K A) (hQ : U * U = Q) : U →ₗ[K] U →ₗ[K] Q :=
  (submoduleProductMultiplication U).compr₂ (LinearEquiv.ofEq (U * U) Q hQ).toLinearMap

@[simp]
theorem submoduleMultiplicationToDegreeTwo_apply
    (U Q : Submodule K A) (hQ : U * U = Q) (x y : U) :
    ((submoduleMultiplicationToDegreeTwo U Q hQ x y : Q) : A) = (x : A) * (y : A) := by
  subst Q
  simp [submoduleMultiplicationToDegreeTwo]

/-- Transport to a named degree-two piece preserves symmetry. -/
theorem submoduleMultiplicationToDegreeTwo_symmetric
    (U Q : Submodule K A) (hQ : U * U = Q) :
    ∀ x y, submoduleMultiplicationToDegreeTwo U Q hQ x y =
      submoduleMultiplicationToDegreeTwo U Q hQ y x := by
  intro x y
  apply Subtype.ext
  simp only [submoduleMultiplicationToDegreeTwo_apply]
  exact mul_comm _ _

/-- If the named degree-two piece is the product of degree one with itself, its symmetric-square
multiplication is surjective. -/
theorem symmetricSquare_submoduleMultiplicationToDegreeTwo_surjective
    (U Q : Submodule K A) (hQ : U * U = Q) :
    Function.Surjective (symmetricSquareMultiplication
      (submoduleMultiplicationToDegreeTwo U Q hQ)
      (submoduleMultiplicationToDegreeTwo_symmetric U Q hQ)) := by
  apply (symmetricSquareMultiplication_surjective_iff_tensorProduct_lift_surjective
    (submoduleMultiplicationToDegreeTwo U Q hQ)
    (submoduleMultiplicationToDegreeTwo_symmetric U Q hQ)).2
  rw [submoduleMultiplicationToDegreeTwo, TensorProduct.lift_compr₂,
    tensorProduct_lift_submoduleProductMultiplication]
  exact (LinearEquiv.ofEq (U * U) Q hQ).surjective.comp
    (Submodule.mulMap'_surjective U U)

/-- Ring-theoretic endpoint for the rank calculation in PDF Theorem 4.3.  For the canonical
multiplication `U × U → U * U` in a commutative algebra, symmetry and degree-two generation
are discharged internally; the remaining algebraic input is exactly the perfect pairing on the
parameter quotient supplied by Proposition 2.2. -/
theorem hankelKernel_eq_parameterSpan_and_rank_of_submoduleProductMultiplication
    (U : Submodule K A)
    [Module.Finite K U]
    (ell : (U * U) →ₗ[K] K) (hell : ell ≠ 0)
    {m c : ℕ}
    (parameters : Fin (m + 1) → U)
    (hparameters : LinearIndependent K parameters)
    (hparametersKernel : ∀ i,
      parameters i ∈ LinearMap.ker ((submoduleProductMultiplication U).compr₂ ell))
    (hAG : ParameterProductPerfectPairingCertificate
      (Submodule.span K (Set.range parameters)) (submoduleProductMultiplication U)
        (submoduleProductMultiplication_symmetric U))
    (hU : Module.finrank K U = m + c + 1) :
    LinearMap.ker ((submoduleProductMultiplication U).compr₂ ell) =
        Submodule.span K (Set.range parameters) ∧
      LinearMap.BilinForm.finiteRank ((submoduleProductMultiplication U).compr₂ ell) = c :=
  hankelKernel_eq_parameterSpan_and_rank_of_parameters_mem_hankelKernel
    (submoduleProductMultiplication U) (submoduleProductMultiplication_symmetric U)
    ell hell (symmetricSquare_submoduleProductMultiplication_surjective U)
    parameters hparameters hparametersKernel hAG hU

/-- Degree-piece form of the ring-theoretic Theorem 4.3 endpoint.  A supplied identification
`U * U = Q` turns the canonical product span into the named degree-two piece, so the original
functional `ell : Q → K` is used without any abstract multiplication or generation hypothesis. -/
theorem hankelKernel_eq_parameterSpan_and_rank_of_degreeTwo_eq_product
    (U Q : Submodule K A) (hQ : U * U = Q)
    [Module.Finite K U]
    (ell : Q →ₗ[K] K) (hell : ell ≠ 0)
    {m c : ℕ}
    (parameters : Fin (m + 1) → U)
    (hparameters : LinearIndependent K parameters)
    (hparametersKernel : ∀ i,
      parameters i ∈ LinearMap.ker ((submoduleMultiplicationToDegreeTwo U Q hQ).compr₂ ell))
    (hAG : ParameterProductPerfectPairingCertificate
      (Submodule.span K (Set.range parameters))
      (submoduleMultiplicationToDegreeTwo U Q hQ)
      (submoduleMultiplicationToDegreeTwo_symmetric U Q hQ))
    (hU : Module.finrank K U = m + c + 1) :
    LinearMap.ker ((submoduleMultiplicationToDegreeTwo U Q hQ).compr₂ ell) =
        Submodule.span K (Set.range parameters) ∧
      LinearMap.BilinForm.finiteRank
        ((submoduleMultiplicationToDegreeTwo U Q hQ).compr₂ ell) = c :=
  hankelKernel_eq_parameterSpan_and_rank_of_parameters_mem_hankelKernel
    (submoduleMultiplicationToDegreeTwo U Q hQ)
    (submoduleMultiplicationToDegreeTwo_symmetric U Q hQ) ell hell
    (symmetricSquare_submoduleMultiplicationToDegreeTwo_surjective U Q hQ)
    parameters hparameters hparametersKernel hAG hU

/-- Internal-graded form of the ring-theoretic Theorem 4.3 endpoint.  The hypothesis
`DegreeTwoGeneratedByDegreeOne 𝒜` is exactly the degree-two consequence of standard gradedness
invoked in the PDF, so multiplication, symmetry, and surjectivity of `Sym²(R₁) → R₂` are all
constructed internally. -/
theorem hankelKernel_eq_parameterSpan_and_rank_of_degreeTwoGeneratedByDegreeOne
    (𝒜 : ℕ → Submodule K A) [SetLike.GradedMonoid 𝒜]
    (hgenerated : DegreeTwoGeneratedByDegreeOne 𝒜)
    [Module.Finite K (𝒜 1)]
    (ell : 𝒜 2 →ₗ[K] K) (hell : ell ≠ 0)
    {m c : ℕ}
    (parameters : Fin (m + 1) → 𝒜 1)
    (hparameters : LinearIndependent K parameters)
    (hparametersKernel : ∀ i,
      parameters i ∈ LinearMap.ker ((gradedDegreeOneMultiplication 𝒜).compr₂ ell))
    (hAG : ParameterProductGorensteinCertificate
      (Submodule.span K (Set.range parameters))
      (gradedDegreeOneMultiplication 𝒜)
      (gradedDegreeOneMultiplication_symmetric 𝒜))
    (hR₁ : Module.finrank K (𝒜 1) = m + c + 1) :
    LinearMap.ker ((gradedDegreeOneMultiplication 𝒜).compr₂ ell) =
        Submodule.span K (Set.range parameters) ∧
      LinearMap.BilinForm.finiteRank
        ((gradedDegreeOneMultiplication 𝒜).compr₂ ell) = c :=
  hankelKernel_eq_parameterSpan_and_rank_of_gorensteinCertificate
    (gradedDegreeOneMultiplication 𝒜)
    (gradedDegreeOneMultiplication_symmetric 𝒜) ell hell
    (symmetricSquare_gradedDegreeOneMultiplication_surjective 𝒜 hgenerated)
    parameters hparameters hparametersKernel hAG hR₁

end ArtinianGorensteinDegreeOneCertificate
